### ISSUE TITLE
'font-size:' in 'pagenum' CSS in the header file should specify an absolute size rather than a relative one

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1003]
**Describe the solution you'd like**
Should 'font-size:' in 'pagenum' CSS in the header file specify an absolute size or a relative one? i.e. 'small' rather than 'smaller'. The page number when displayed in a browser should be the same size irrespective of whether it is in, say, blockquoted text which displays in a smaller font size, or normal paragraph text which displays in the normal font size.

There is the related issue of having to adjust the alignment of the page number which is in the middle of blockquoted text (with a smaller font size) so that it aligns with the page numbers in normal paragraph text. 

If I understand things correctly, the second issue can only be fixed by the PPer defining multiple versions of the 'pagenum' CSS so that the appropriate version is used in context; that is, one for normal paragraph text, another for blockquoted text displaying in a smaller font and one (or more) where the page number is in the middle of a table. 

But, if you are bothering to adjust for this second issue, then I suppose it is no problem to also specify 'small' rather than 'smaller' in each of the different versions of 'pagenum'. 

**Describe alternatives you've considered**
If there is a simpler way to have all page numbers correctly aligned and in the same font size when displayed in a browser then I would welcome being shown how!

**Comment by windymilla** [comment]
I definitely agree about the first suggestion (small/smaller). Do you have an example of the second issue? A change was made (#900) to set the text-indent to zero for a similar purpose. I thought the way pagenums were positioned, (`absolute`ly) meant that they weren't dependent on margins. Happy to look at it with an example file.

**Comment by G4OEU** [comment]
See attached example file. The page numbers with a blue border have _font-size: small;_ in the CSS. The page numbers with a purple border have _font-size: smaller;_ in the CSS. 

The first sentence in each paragraph explains its purpose.

Just change file type to .html and display in a browser.
[pagenum-exampler.txt](https://github.com/DistributedProofreaders/guiguts/files/9600511/pagenum-exampler.txt)

**Comment by windymilla** [comment]
Thanks. Maybe that CSS header is one adapted from release 1.3 or before. In release 1.4 onwards, pagenum has the following CSS line:
```
text-indent: 0;
```
If you add that, I think your blue pagenums all look fine. If you also change pagenum1 to "small" instead of "smaller", then the purple ones look fine too.

Let me know if you agree - I'll change "smaller" to "small" in the default header anyway.

**Comment by G4OEU** [comment]
I agree that has fixed it. 

I have been using adapted header code copied from earlier books. Presumably this predated 1.4.0.

Thanks for pursuing this. The newer pagenum CSS will save me a lot of time in subsequent books!

**Comment by windymilla** [comment]
If at all possible, I recommend adapting the default header to your own preferences in a way you can easily transfer your changes to a new release. Otherwise it's hard to get the benefit of potential improvements.
One way that would work for most such changes is to put all your customizations at the end of the file, e.g.
```
/* My customizations */
.pagenum { border: 3px solid blue;}   /* I like a blue border on my page numbers */
.tdct     {text-align: center; vertical-align: top;}  /* Useful table cell formatting */
.tdcm     {text-align: center; vertical-align: middle;}
.tdcb     {text-align: center; vertical-align: bottom;}
```
Then when you get a new release, copy that whole section to the bottom of the new release's `header.txt`

**Comment by G4OEU** [comment]
I will try that approach. Thanks.
