### ISSUE TITLE
HTML Auto Illus. Search: Add option to generate HTML5 <figure> and <figcaption> tags.

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#1045]
Even better (perhaps a separate request), I would like to customize the replacement code. With 500 illos, it is not practical to edit each one in the menu process. I'll probably see if I can modify the code, but it would be better to have a user friendly option.

**Comment by windymilla** [comment]
Could you upload an example file, with the HTML that you would like GG to produce please.

Or is it literally a case of taking
```
<div class="figcenter illowe62_5" id="xyz">
  <img class="w100" src="images/xyz.jpg" alt="">
  <div class="caption"><p>XYZ picture caption.</p></div>
</div>
```
and changing `div` to `figure` or `figcaption`?
What happens about figleft/center/right?

Is there a reason we should not just switch over to using the new tags, rather than providing an option? GG already has many, many options, which complicate the code and documentation, so if the new tags are better, we could just use them.

As for the "customization" option - what type of thing are you thinking of? As you say, it might be better as a separate request, but if I know what you are after, I could be pondering it.

**Comment by rtonsing** [comment]
The W3C has a good description [here](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-figure-element.html). The "Here we see a figure element to mark up a photo" exactly matches how I use it.

I think the advantage is that it does a better job of keeping the contained elements (image, caption) together on the same page. With the old method I consistently see them split in epub readers. I have not done extensive testing, though.

I would say to just switch to the new tags, pending input from other users and more testing.

**Comment by rtonsing** [comment]
For the customization option, there are things like the `<p>` tags on the captions that I prefer not to include, and changes to the `<img>` attributes.

**Comment by windymilla** [comment]
Thanks - I'll have a go at the figure/figcaption bit.

**Comment by windymilla** [comment]
For the customization, because it would be quite a significant bit of work, and complication to the code/documentation, can you give me some more detail, by PM/email if you prefer. I'd like to get to the bottom of the reasoning, i.e. what you actually want to achieve. For example, is it just that you think having a `<p>` in the caption is superfluous, or is it causing styling issues that you don't like? What type of `<img>` attributes are you wanting to change & why? Thanks

**Comment by rtonsing** [comment]
I think the `<p>` is both superfluous, and applies margins, indent, etc. that I would rather control by CSS for `<figcaption>` or a class. Will take a look again at `<img>` later.

**Comment by windymilla** [comment]
Thanks - another possibility might be to style `<p>` that are children of `<figcaption>`:
`figcaption  p  {font-weight: bold;}`
