### ISSUE TITLE
Ruler like Microsoft Word

### ISSUE THREAD

**Issue by btaylor289** [DistributedProofreaders/guiguts#1057]
Could we have a ruler on the bottom of the window showing a ruler like Microsoft Word?  I was thinking it could display column numbers.  Maybe make it clickable and show a line on window.  Would be helpful when working on wide tables in text mode.

Or maybe add a highlighted area to the right of the Max. Right Margin setting making it easy to see how close you are to the right margin.

**Comment by windymilla** [comment]
A ruler might be possible, a bit like the line numbers that you can get down the left hand side (Prefs/Appearance/Display Line Numbers). Would be quite a bit of work though, and integral to the handling of the main text widget, rather than a simple addition. Drawing a line or highlighting where there is no text is not easy (see below) but there is a feature for highlighting where there is text (details below).

There are a couple of other features that may be useful, or maybe even sufficient for what you want:

The first is that the column number is always displayed in the status bar (left-most label shows row/column).

The second is in the Search menu: Highlight Alignment Column (shortcut is Ctrl+Shift+a). This displays a green highlight line at the current cursor column. It's easier to see than describe - just put your cursor in the middle of some text and use Ctrl+Shift+a. As you move the cursor or edit the text, the vertical alignment line should remain at the column you requested. You can turn it off and display it a different column by repeating the keyboard shortcut or menu option. You could use this to mark column 70, for example, and whenever your lines were longer than 70 you would see the highlighting on the long line. As mentioned in first paragraph, it can't highlight column 70 on lines that are less than 70 characters long (at least not without major work which wouldn't be justified)

Finally, I don't know if you have got into the Txt/Ascii Table Effects dialog yet ([excellent manual page](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Text_Menu#ASCII_Table_Effects)). I know it is used successfully by PPers attempting to wrangle tables into a suitable text format.

One other trick I've used (prior to adding the Highlight Alignment Column feature) is to simply resize the window so that it is 72 columns wide (for example) which gives similar assistance to your highlighted area to right of Max Margin idea.
