### ISSUE TITLE
Guiguts 1.5.1 (newest update) Word Frequency - All Words

### ISSUE THREAD

**Issue by hekula03** [DistributedProofreaders/guiguts#1063]
Always I go into 'Word Frequency'. I check 'All Words' looking for characters not suppose to be in a word. I'll check 'Emdashes' normally quite boring. In the case yesterday, I had a 'suspect word (in 'Emdashes'). 'Dining-room' (with a hyphen). This word is really correct. If I go to my .txt file, this is what I see: <sc>Act I.</sc>--Dining-room. (I am still in the 'pre-split' stage.) 'Dining-room' is preceded by a -- (hyphen hyphen) which is the problem.

From what I understand this is a bug (somewhere in GG, the algorithm(?)). A person check this out in Guiguts 1.0.25. This bug was present.

Thank you.

**Comment by windymilla** [comment]
Hopefully fixed by the linked issue. 
The purpose of the Emdash check is to ensure you don't have `Dining--room` and `Dining-room` in the file (i.e. with a single hyphen and with a double hyphen).
The example file has `...</sc>--Dining-room`
Since HTML tags are converted to a space for the purposes of Word Frequency, this is equivalent to the word being `--Dining-room`. This should not have been counted as a double-hyphen word, since it is just a word that happens to come after a double hyphen - the double hyphen isn't joining it to another word.
