### ISSUE TITLE
Suggestion to remove limit in the page number string length limit of 10

### ISSUE THREAD

**Issue by Patoruzu45** [DistributedProofreaders/guiguts#1077]

**Comment by windymilla** [comment]
Hi Andrés

This isn't the right place for this issue because it is ebookmaker that has the page number string length limit, not Guiguts.
The place I linked in the forums to add your issue was here: [https://github.com/gutenbergtools/ebookmaker/issues](https://github.com/gutenbergtools/ebookmaker/issues)

**Comment by Patoruzu45** [comment]
Hi Nigel

 

Sorry for the mistake! How can I fix it? Do I need  to delete the issue?  and post it where you are saying?

 

Thanks.

 

“No esperes nada del hombre que lucha por su vida y no por su eternidad”

 

Antoine de Saint Exupery

 

 

“La Humanidad achaca todas las calamidades a la acción de los malvados. Subestima a los estúpidos”

 

A.  Bioy Casares

 

 

«El que se inclina ante los poderosos muestra su trasero a los oprimidos»

 

Millor Fernandes:

 

 

“Todos los hombres dicen más o menos lo mismo. Sólo sus acciones permiten ver en qué difieren”

 

Molière

 

"Yo no creo en las sociedades maravillosas y perfectas que dan malos dirigentes. Hay un poco de reflejo."

 

El enmascarado solitario

**Comment by windymilla** [comment]
Yes - that would probably be the easiest.

**Comment by windymilla** [comment]
Issue has now been entered at [ebookmaker](https://github.com/gutenbergtools/ebookmaker/issues/155)
