### ISSUE TITLE
"Unmatched Brackets Check" overlooks some missing brackets

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1113]
(This is a contrived example....) In the attached file, there's a missing closing parenthesis, then, much later, a missing opening parenthesis. In between are matched parentheses.  The new "Unmatched Brackets Check" thinks the early opening parenthesis matches the later closing parenthesis and reports no errors, which is incorrect.

This happens with other brackets, as well as with "Unmatched Block Markups." (No sample provided for Blocks, but it's very easy to reproduce.)

May be an unintended consequence of supporting nesting. "No good deed...."

The existing "Check Orphaned Brackets" on the Tools Menu finds all of them.

[unmatchedbracketsbug.zip](https://github.com/DistributedProofreaders/guiguts/files/10830277/unmatchedbracketsbug.zip)

**Comment by windymilla** [comment]
Are you saying that you don't want nesting to be allowed? 
Those parentheses do all have matches if you're permitting nesting.

So, are the following examples unmatched? Or more pertinently, do you want the checks to report them as errors?

`(Some (nested) brackets)`
or
```
/#
/#
Quote within quote
#/
Outer text
#/
```
or
```
<div class="poetry">
<div class="verse">
Line of poem
</div>
</div>
```
or
`<i>Some <i>italic</i> text</i>`

Or do you want different nesting rules for different types of check? Hopefully, if I know what you want, I'll be able to implement it.

**Comment by charliehoward4dp** [comment]
I'm now thinking that there isn't one right answer to this, and that our best solution comes in two parts:

1. Leave the new "Unmatched" checks as they are, with their much-needed nesting support.  Keep the existing "Check Orphaned Brackets", which finds consecutive identical tags.

2. In the documentation for each of these, explain their advantages and limitations.

**Comment by windymilla** [comment]
I've continued to ponder the last line of my previous comment, which is whether all the checks should have the same nesting rules. They currently do because I re-use the same code for them all. 
However,
1. I don't think `<i>Some <i>italic</i> text</i>` is valid in a pre-split file (the Tools, Unmatched Tags entry).
2. More often than not, nested brackets would indicate a potential error that the PPer should check manually. 
3. Some block markup is not permitted to be nested. Block quotes are, but you can't put `/R` inside `/R`, for example.
4. Nesting in HTML definitely needs to be permitted - I know <body> can't be nested, but TBH, contrived errors like that aren't what we're trying to trap; it's things like p, span, div, etc., so I think current behavior is correct in the HTML check.

I'll have a look at making changes to implement the above. Even though it would mean the manual might need to be explicit about whether nesting is trapped for each report type, that would be worth it to avoid errors sneaking through and/or PPers having to do the new check and the old check, and potential future bug reports that a case wasn't trapped by the new check, but is by the old check.

**Comment by charliehoward4dp** [comment]
If (and only if) you decide to distinguish between required and optional closing tags, here is a list I found of the optional ones in HTML.  Presumably, that means they cannot be nested within themselves.  I don't know for sure that it is authoritative or complete, and it doesn't include the self-closing tags, such as `<img>` and `<br>`:

`<html> <head> <body> <p> <li> <dt> <dd> <option> <thead> <th> <tbody> <tr> <td> <tfoot> <colgroup>`

From a nesting standpoint, the challenging ones in that list are the ones used in tables, because tables can be nested within tables. However, that occurs so rarely that I think we can ignore such cases and treat them as non-nestable.

DP's tags are easier: all tags except for `<tb>` must be closed and none except /#...#/ may be nested within themselves.

Square brackets and parentheses occasionally occur unpaired in "credit" lines below illustrations, and right-square brackets commonly are used unpaired in Stage directions. However, since finding unmatched brackets is both important and difficult to do visually, I'd much rather have false positives in the list than deal with omitted false negatives.

The draft copy of the documentation for the next release already addresses the way the next release currently handles unmatched tags/brackets/block markups, giving the advantages and limitations of both the old (no nesting support) and new (with nesting support) tests.  That may be sufficient, IMO.
