### ISSUE TITLE
Word Frequency mishandles combining characters

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1114]
**Describe the bug**
**MiXeD CasE**, **Check Accents**, and **Check Spelling** buttons in Word Frequency (only those buttons were tested) will, in one case, displace the combining character when the word containing it in the report is double-clicked and the text with that the word is displayed.  In the other case, where there is no precomposed Unicode equivalent for the combined character, the word in which the combined character is contained is truncated in the report that is produced by each of those three buttons above.

See below for examples of this.

**To Reproduce**
1. Open Guiguts with 
[WF-error-example.txt](https://github.com/DistributedProofreaders/guiguts/files/10833912/WF-error-example.txt) 2. Open the Tools>Word Frequency menu and click the MiXeD CasE button. Scroll down the report to the line with 'Shui-Hsien-Tszu' (no breve on top of the last 'u'). Double-click that line and you will see that the breve is shifted in the display (but missing in the report). This is the UN-NORMALISED text.
3. Double-click on the next line in the report which contains 'Shui-Hsien-Tszŭ' (breve on top of the last 'u'). The precomposed character that has replaced the combined character displays correctly in the second paragraph. This is the NORMALISED text.
4. Next, go back up the list to the line that says '2    en-Hou'. Double-click then double-click again. An instance of the name 'Ti̔en-Hou' is displayed in the third and fourth paragraphs. Note how the MiXeD CasE report only lists the part of the word after the combined character. In some other WF reports, the part of the word _before_ the combined character might be displayed. The truncated word in the report is the same, whether the original word (and combined character) is normalised or not.
5. The combining characters used are COMBINING BREVE (U+0306, 774 Dec) in the first two paragraphs, and COMBINING REVERSED COMMA ABOVE (U+0314, Dec 788) in the second two paragraphs.
6. It turns out there is a precomposed Unicode character for u+breve which I only later discovered. Don't know whether this is relevant to the fact that i+reversed comma above does not have a Unicode precomposed equivalent.

**Expected behavior**
(1) That Word Frequency should display combined characters as if they have been normalised when a report entry is double-clicked; 
(2)  Display words with combined characters correctly (i.e. not truncated) in the reports produced by the WF buttons.

**Environment**
* Guiguts version: From at least 1.4.0 to 1.5.3-test3. Likely present in 1.0.25 also.
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
Notes on your points...
1. There are two reasons I won't do anything about this particular one: using un-normalised characters is not supported; also, the movement of the accent (which will also happen in cases where there is no normalised form) is a limitation of the main text window. Just selecting via click and drag can also make that happen, or I've also seen it when you use arrow keys to step the cursor through a word with combining characters. Once you remove the orange highlighting (Ctrl+zero) the accent jumps back. It think it's because the accent is not part of the selected word, so it shouldn't be in orange, so it gets moved, or something like that - buried inside code we have no control over anyway.
2. That is describing correct behaviour, so nothing for me to do :)
3. Looks like WF is not considering the combining characters to be normal word characters, which they should be I guess. As I intimated previously, the core of the WF code has been very stable, but I'll delve in and see what I can do.
4. and 5. Nothing for me to do.

So, if I can fix point 3, I think it will be as good as we can get, and words will not get split at combining characters.

**Comment by srjfoo** [comment]
This may not be relevant to the current issue, because it is about using **_multiple_** combining diacritics. However, I thought it worth mentioning that even within one application that supposedly handles combining diacritics, what you actually get depends somewhat on the font. Of the list of different fonts, the best were Arial, Microsoft Sans Serif and Times New Roman. The worst were DP Sans Mono, Georgia and Verdana. Everything else was in between. (The worst of the examples, obviously, the `u` with combining grave and haček/caron, which is likely not something you'd see in real life, but is useful as an example.)

![image](https://user-images.githubusercontent.com/36800239/221437838-0c1f280e-94cb-43e6-88e9-97e1f1b01e5d.png)

When copied and pasted into GG, this screenshot shows the separate characters with their combining diacritcs:
![image](https://user-images.githubusercontent.com/36800239/221438700-dab52e21-5701-4f3b-b990-93a1677f2fd6.png)
and this one, the normalized forms:
![image](https://user-images.githubusercontent.com/36800239/221438746-fd62b45e-cace-46aa-81fc-5137957beaf0.png)

**Comment by G4OEU** [comment]
Re. point 1 I thought you would probably say 'normalise' and the problem goes away! I also did not understand why the combining character in paras 3 & 4 was not displaced as in paras 1 & 2 but your reply explains this; that is, the bug referred to in my point 3 means the combining character is not actually part of the selected/highlighted word.

I accept your response to my point 1 but I think the requirement to normalise combining characters needs to be emphasised in the Wiki page on combining characters. The GG Manual does make this point well in the Tools->Character Tools sub-menu page but unfortunately the Wiki page links to the Unicode Menu page in the manual, not the Character Tools sub-menu, and the Unicode Menu manual page says nothing about normalisation.

Re. point 3, we agree on this and I hope you can fix it.

Getting back to point 1, if there are strong reasons for normalising characters then there is also a strong case for there being a tool that checks for un-normalised characters in a text file.  Charlie says in the Character Tools sub-menu page that "Nu HTML Checker used by Guiguts and Project Gutenberg will issue warnings about decomposed characters if an equivalent precomposed Unicode character exists". However this is no help as I was encountering problems with un-normalised characters much earlier in the PPing workflow, namely while I was preparing the common file before it is split. That is when checks for un-normalised characters should be done? Perhaps PPTEXT is another place where un-normalised characters can be flagged?

**Comment by G4OEU** [comment]
PS I just clocked that I uploaded the wrong file in my original GitHub post. It should have had just four paragraphs. Sorry about that.

**Comment by srjfoo** [comment]
>... as I was encountering problems with un-normalised characters much earlier in the PPing workflow, namely while I was preparing the common file before it is split. That is when checks for un-normalised characters should be done?

You should not be getting an un-normalized form for which a normalized form exists in the PP files that DP provides. If you are, please let me know what it is so I can investigate.

Yes, the normalization should be done in the common file before the split.

**Comment by G4OEU** [comment]
Sharon, I should clarify that the un-normalised characters were ones that I had constructed and had failed subsequently to normalise. Their construction was in response to encountering proofreading symbols from the rounds such as **[,i]** and **[)u]**. 

As a BTW, in the case of the **[)u]** (u+breve) that appeared from the rounds, I don't know why they didn't use the precomposed symbol U+016D. There were dozens of other characters with diacritical marks for which they found the correct precomposed character but not this one! Could it have it been missing from the Unicode character tools they use?

**Comment by srjfoo** [comment]
`ŭ` is in the [Extended European Latin A](https://www.pgdp.net/c/tools/charsuites.php?charsuite=extended-european-latin-a) character suite with the normalized code. If a PM tried to add the un-normalized form in a project-specific character suite, it would have been normalized. Which project was it, and what character suites are part of the project?

**Comment by srjfoo** [comment]
Oh, nevermind, I misunderstood.

This is just a guess, but ... when you do OCR, the more character sets you allow, the more likely you are to get things OCR'd incorrectly. If they limit the project character suite to Basic Latin because 99.9%+ of all the characters are in that character suite, there's less room for error. If there are only a handful of characters that require special treatment, it often makes more sense to use the special character markup and have it converted in PP.

As an example (though using a Greek character suite wasn't an option then), my first PP project had one phrase in Greek. On the title page. At that point, it had to be transliterated, but if the book were being run now, the PM *could* use the Polytonic Greek character suite. Or could stick with requesting transliteration. If it were me, and I were running it now, I'd opt for transliteration, because it's one phrase, on one page, and there are too many opportunities for confusing combinations.

Not knowing which project caused you such grief, I don't know if that's the reason, but that's my guess.

**Comment by G4OEU** [comment]
Nigel, I withdraw my suggestion for a tool to flag un-normalised characters, in text files, where there is a precomposed equivalent. I now don't think it is needed.

I have re-read Charlie's qualification/warning ("Technical note on Greek oxia/tonos") in the manual for people contemplating normalising the _whole_ file. It seems to me to be a very limited and niche issue which should probably be ignored in any case if DP policy on Greek is being properly followed.

Instead there should be a _strong recommendation_ to run the existing **Normalize Selected Characters** in the Tools>Character Tools sub-menu on the whole file (i.e. Ctrl+a first). What do you think?

**Comment by windymilla** [comment]
You should only need to do that if you as a PPer have inserted Combining Characters. If you haven't been using them, then there will be no problem with normalization. So, I don't think it needs to be a general recommendation, but if there is somewhere in the manual that described combining characters, it should recommend it there.

**Comment by G4OEU** [comment]
We have just cross-posted at the same time! There is a recommendation of sorts [here](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Tools_Menu#Normalize_Selected_Characters) in the Character Tools sub-menu page of the manual. Is it worth discussing the current wording with Charlie to see whether it needs to be tweaked? You and Sharon will have a much better overview of this issue than me.

It would have helped me avoid some grief as a first-time user of combing characters if I had been sent from the [Wiki page ](https://www.pgdp.net/wiki/Combining_characters) directly to the manual page above, rather than to the Unicode Menu manual page.

**Comment by windymilla** [comment]
Fixed by #1115
