### ISSUE TITLE
Find Proofer Comment doesn't show cursor when using tear-off menu

### ISSUE THREAD

**Issue by rtonsing** [DistributedProofreaders/guiguts#1128]
**Describe the bug**
When using the comment search items from a tear-off menu, the editor does not show a cursor or highlight at the found item. Sometimes the item is at the center of the page, but often not, so I have to look for it. When **not** using the tear-off menu, the cursor is moved to the item. Not a severe issue, but annoying.

**To Reproduce**
1. Open Guiguts
2. Open the Search menu
3. Click on dashed line to tear off menu
4. Click on "Find Next Proofer Comment"
5. View is moved to location, but there is no cursor. Item may be anywhere in the page.

**Expected behavior**
Flashing cursor at start of found item.

**Environment**
Currently Running:
Guiguts, Version: 1.5.2
Platform: MSWin32
Microsoft Windows [Version 10.0.22623.1325]
Perl v5.32.1
Aspell 0.50.3
perl/Tk Version: 804.036
Tk patchLevel: 8.4
Tk libraries: C:/Strawberry/perl/site/lib/Tk

**Comment by windymilla** [comment]
Thanks
Note to self: this also applies to the Find asterisks menu option and maybe others.

Since I'm not planning to fix this in the version which is ready for release now, if you want to manually fix it in your code - you need to add 
`        $textwindow->focus;`
as the last line of the routine `find_proofer_comment` in `SearchReplaceMenu.pm`

Alternatively, you can click on the border/banner of the main text window - it's just a case of getting the text window to have focus. Some searches do it, but not others - I'll make sure they all do.
