### ISSUE TITLE
Replace-all over a range of lines doesn't process the entire range

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1189]
Here is an old bug that has resurfaced in GG 1.6.0; it doesn't happen in GG 1.5.3. It's easily reproducible using the attached file and the regex below.

Go to bookmark 1 on page 21. The input to AutoTable was improperly formatted (by me .. didn't leave 2 spaces between columns), so instead of a right column and a left column, there's just one column.  The regex below should split each `<td>` into two `<td>s` ... but it stops before reaching the end of the selected range.

Here is the Search argument: `"tdr">(\d) (.+?)</td>`
Here is the Replace argument: `"tdr">$1</td>\n<td class="tdl">$2</td>`

1. Select the table. It begins on line 1856 and ends on line 1977.
2. click Rpl All

The last ten rows of the table are not replaced.  If the entire table is selected again and Rpl All is clicked again, 8 of the 10 are processed, still leaving the last two unprocessed.

If R&S is done manually, it works fine. if nothing is selected, but the cursor is positioned at the top of the file and Rpl All is clicked, it works fine.  So, it only fails when a somewhat long range is selected.

[searchreplacebug.zip](https://github.com/DistributedProofreaders/guiguts/files/11240800/searchreplacebug.zip)

**Comment by windymilla** [comment]
Thanks - definitely a bug.
Please could you check again in 1.5.3 - when I do that, it seems to go wrong there too, ending with the change on line 1975.

I think I know the problem, but it would be good to know if it really did work OK in 1.5.3 (possibly never has)
I think it's because it first remembers the line numbers it needs to start and stop at (1856 to 1977), but because each replacement adds a line, when it stops at line 1977 there are still lots of lines left to do.

**Comment by charliehoward4dp** [comment]
You are correct: the bug is present in 1.5.3, 1.4.0, and 1.3.0 (didn't check earlier than that).
