### ISSUE TITLE
Guiguts removes end-of-line spaces when saving a file

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1213]
Guiguts removes end-of-line-spaces when saving a file. This includes removing ending hard spaces.

Well, this isn't a bug, and until recently, it was a benefit.  However, in order to force page-breaks in epub, it's necessary to pad short sections with whitespace, as explained in [THIS](https://www.pgdp.net/phpBB3/viewtopic.php?p=1301717#p1301717) post.

IMHO, any selector with the "page-break-before" property should trigger a page break in epub, even if there are zero characters in the section/chapter/paragraph/division, or whatever.  But that's not the way EBM works right now. 

Is there a workaround?  Some form of "whitespace" that Guiguts will not remove and EBM will recognize?

**Comment by srjfoo** [comment]
Do these markers have a particular class that identifies them as uniquely needing to have the whitespace retained?

**Comment by charliehoward4dp** [comment]
Yes. The original post, which is quoted, says to use the "section" selector as a marker. In addition, all of my CSS uses the "page-break-before" property with the .chapter, .newpage, and .section selectors.

The very last step in my PP procedure is to make sure "section" appears in the "class" of everything I will want to start on a new page, and then to add at least four lines of 64-characters of spaces at the very end of each of those sections.  I've been doing that ever since the quoted guidance appeared in December of 2022, and have wondered why it works with some ereaders and not with others.  My assumption, until today, was that it was the fault of those ereaders, and that may be true; but today, I found that Guiguts is removing all trailing spaces, including hard spaces, so those lines of 64 spaces are saved as lines of zero spaces.

**Comment by charliehoward4dp** [comment]
jjz suggested an easy-to-do workaround (place an &nbsp; at the end of each line of spaces), so I'm closing this.

**Comment by windymilla** [comment]
Thanks @charliehoward4dp & jjz. 
So that all relevant information is in one place, here are a couple of notes on this issue:
-  Trailing tabs, spaces and actual non-breaking space characters (not HTML entities) are indeed removed from every line before it is saved to file
- The addition of space characters is only needed where the "chunk" of HTML would otherwise be less than 256 characters long, because ebookmaker will not start a new chunk until the old chunk reaches at least 256 characters. Strictly, you would just need to add enough space characters to increase the old chunk size to 256.
- The [post](https://www.pgdp.net/phpBB3/viewtopic.php?p=1301717#p1301717) linked in the issue description suggests using a dummy section div, rather than padding an existing short section, but either should work. The code from the original post would not cause the bug described in this issue, since the suggested line does not end with whitespace. 
`<div class='section'>{250 or so characters of whitespace}</div><div class='section'>..... `
However, it does lead to a long line of HTML, which Charlie's adjustment avoids.

**Comment by windymilla** [comment]
Re-opening...will implement a fix so that trailing spaces are only stripped from `.txt` or `.text` files
