### ISSUE TITLE
Bug or feature? Inserting a character from Unicode Character Search behaves differently to inserting from Commonly Used Characters

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1233]
**Describe the bug**
If a group of characters are selected on a line in the GG window and you left-click a symbol from the Unicode Character Search dropdown, that symbol is _appended_ to the selected text rather than replacing the selected text.

On the other hand, if you instead left-click a symbol from the Commonly Used Characters dropdown, that symbol _replaces_ the selected text in the GG window.

**To Reproduce**
1. Open Guiguts
2. Create a line of random text
3. Select some characters within the line
4. Perform sequences described above
5. See the different behaviours

**Expected behavior**
I would expect the selected text to be _replaced_ by the symbol chosen from either dropdown

**Environment**
* Guiguts version: 1.6.0
* OS and version:  Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
Behaves similarly in 1.4.0 and, I assume, in earlier versions too

**Comment by windymilla** [comment]
It's a bug. Most of those character tools use a specific function for inserting the character, which does delete the selected text before inserting the character. However, the Unicode Character Search that you found (and the Unicode Character Entry dialog which I spotted while fixing this) just used a plain "insert" rather than the special function. Thanks
