### ISSUE TITLE
After body text has been manually modified, regex sometimes errs in selecting what's in the modified area

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1235]
It seems that, for overall efficiency, a new regex pre-scans the entire body of text and stores pointers to all of the matches before displaying the first one. (Or maybe it only does this when a newline is in the search argument?) Whether or not this really is the implementation, the following situation arises:

1. a match somewhere in the middle of all the matches is found.
2. user makes manual changes to the text and [optionally] continues searching.
3. user does a few Reverse searches (probably to make sure `#2` didn't occur earlier).
4. user resumes Forward searches.
5. when the manually-modified text (`#2`) is found again, too little or too much text is highlighted, because the length of the original matched area was changed. NOTE: if the text is changed by using Replace, I think this erroneous selection will NOT occur.
6. this erroneous selection continues until the furthest-modified area has been passed; remaining matches are highlighted correctly.
7. If user selects "Start at Beginning" (or just goes back to the top of file manually), the searches will select the correct matching text, even when in the areas that were modified.

`#7` is a workaround, and instead of attempting to prevent the erroneous selection from occurring, we could document the workaround.

This doesn't happen in Notepad++, but that isn't using Perl.

**Comment by windymilla** [comment]
I can see the issue, but I don't see any way GG could know in general what bit you wanted it to select if you've modified it. 

The only "logical" solution would be to still insist that the pattern should match (as happens if you don't have `\n`), then after you've modified it the pattern might not match so it would skip over that position.
Example - if the file contains:
```
abc

abc

abc
```
and you do 
Search: `bc\n`
After finding the second occurrence, you change `abc` to `xxxxxxx`
Then search backwards - it finds the first occurrence.
Then search forwards - if finds something in approximately the place of the second occurrence, but of course it is not matching `bc\n`. 

Would you want it to skip over the `xxxxxxx` because it no longer matches `bc\n`? That's what happens if you don't have the `\n`, because it hasn't pre-searched for all occurrences in the file.

I don't see any way of keeping the current "pre-search" (which is solely for the sake of speed- so it only has to concatenate the whole file into a string once once) and also either skipping (for consistency with non `\n` searches) or selecting the "part the user was thinking of now they have modified it".

The problem is that the Tk Text widget doesn't support search matches across a line break, so the concatenation is necessary in order to allow multi-line matches.

I'm afraid that unless I've misunderstood, it's going to just have to be documented, not fixed, sorry.

**Comment by charliehoward4dp** [comment]
I suspected it was in Perl, beyond the control of Guiguts.  I'll document this and close this suggestion.  Thank you for such a quick, thorough explanation.

**Comment by windymilla** [comment]
Thanks Charlie
