### ISSUE TITLE
Add a keyboard shortcut for the "#" button in Quick Search

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#1238]
It would be convenient to have a keyboard shortcut for the "#" (Count) button on the Quick Search  dialog. Key should be ignored if QS is empty or not on-screen.

`<alt>+<shift>+b` is somewhat similar to the two existing Count shortcuts, but that’s just one possibility.

**Comment by srjfoo** [comment]
@windymilla -- remind me, where did we map alt to for Macs (at least for those keyboard shortcuts that actually work on Macs)? Iirc, the normal mapping is alt on Windows is approximately equal to option on a Mac, and option on Macs triggers dead keys for default keyboards.

**Comment by windymilla** [comment]
@srjfoo - the key used instead of Alt is `Meta` in the code, displayed to the user as `Command`.
For example, `Alt-Mouse-1` on Windows is `Command-Mouse-1` on a Mac, used in the errorcheck dialog to pop the Search dialog prepopulated with the queried word (e.g. after using Spell Query)
Another example is `Command-RightArrow` to indent a line of text.

**Comment by windymilla** [comment]
@charliehoward4dp - currently we have
```
<ctrl>+f -- open Search & Replace popup
<ctrl>+b -- count number of matches
<ctrl>+<shift>+f -- open Quick Search popup
<ctrl>+<shift>+b -- quick-count number of matches to highlighted word(s)
```
There is a danger with introducing yet another count keystroke, in that if you choose the wrong keystroke, it will give you a count, but actually doesn't say what it's a count of (more on that later)
I wonder if it would work to also use `<ctrl>+<shift>+b` for counting the Quick Search string? At the moment, it counts the matches to the highlighted word. Here's one way it could be done (1, 2 & 3 seem relatively uncontroversial):
1. If the QS dialog is not up or it is up but has no text in its search field, it would work as currently, counting the highlight matches if anything is highlighted.
2. If the QS dialog is up (with text in it) and your focus is in the QS dialog, then it would count QS matches. (Aside: it currently fails to count the highlight matches if you use `<ctrl>+<shift>+b` with focus on the QS dialog - seems to search for something it can't find - probably a bug).
3. If the QS dialog is up, but focus is in the main window, *but* there is no highlighted text in the main window, then count QS matches (would currently do nothing if no highlighted text, so may as well do something useful)
4. I think the only possibility left is if QS dialog is up, contains text, but focus is in main window *and* text is highlighted. Two options:
    a. Do a QS count
    b. Do a highlight count

If all the above is correct, then to decide if it's a good idea, you'd need to consider if you actually need both 4a and 4b, since that wouldn't be possible with the re-use of `<ctrl>+<shift>+b`. Maybe just 4a or 4b would work for the vast majority of cases, which might mean having `<ctrl>+<shift>+b` as "Quick Count" would be acceptable. The manual would say something like:
"does a quick count of the word(s) in the QS dialog if it has focus, or the highlighted word in the main window if not" (case 4a) or it would say something like "does a quick count of the highlighted word in the main window, unless nothing is highlighted or the QS dialog has focus when the QS word is counted" (4b)

Alternatively, and maybe even more easily comprehensible, "does a quick count of the QS word or the highlighted word in teh main window - if the QS dialog is active and there is also a highlighted word, the QS dialog takes precedence" (or "the highlighted word takes precedence").

What do you think?

Final thought: it might be possible to add a new keystroke similar to what you suggest, but also to make `<ctrl>+<shift>+b` use the QS dialog in the uncontroversial situations, when it would currently do nothing or the wrong thing.

**Comment by charliehoward4dp** [comment]
Yes, if you can tell which window has the focus, then `<ctrl>+<shift>+b` should work and be the easiest for users. Option 4b should be used, as it's the way things work now.

For safety, I think  `<ctrl>+<shift>+b`  should be used for QS only if QS has the focus and has content; otherwise, the shortcut should do whatever it does now.

The reason for this is just to have a more flexible version of quick count, one that isn't restricted to whole words (and has the regex / nocase options as well).  Highlighting something and then pressing  `<ctrl>+<shift>+f`  and then  `<ctrl>+<shift>+b` would be very quick and convenient.

**Comment by windymilla** [comment]
Unless I'm mistaken, it looks like I already provided the feature you are requesting - if QS has focus, and content, then either `<ctrl>+b` or `<ctrl>+<shift>+b` does a count of the string in the QS text field.
I was just checking out what the current situation was when I discovered the shortcut, which is the equivalent of pressing the `#` button :)

**Comment by charliehoward4dp** [comment]
I discovered that 30 seconds before your message posted, and was composing something about it when your message appeared.  The Quick Count pop-up's Title is "Count."  Perhaps that Title could be "QS Count" or "Quick Search Count", to distinguish it from the main window's "Count".

**Comment by windymilla** [comment]
Haha, I was just composing a message to you wondering if it would be better if the Count popup had the word in that was being searched for. It would make sense to make it a bit wider than it is in that case, or it gets abbreviated. For example, I made a quick code change and searched for "Motor" and it showed "Count: Motor" in the title, but searching for "Motor Boat" showed "Count: M..." which is no use. Although you can resize the popup, it pops back up small the next time it is used. If it was wide enough to show, say 10 letters plus the ellipsis, would that be an improvement? 
Or if you prefer, I could just make it say "QS Count" as you suggest

**Comment by charliehoward4dp** [comment]
I sometimes use QS to look for phrases, not just single words, and strings that contain markup tags.  Just changing the Title would be sufficient: it's a visual cue.

The three "Count" functions sometimes seem to come up with different results, and I'm making some tests now to see if that's GG or me.

**Comment by windymilla** [comment]
AFAIK, if you have the settings the same, then normally S&R dialog and QS dialog should do the same counts. There is an exception, which is if you have done something that creates a word list (like the Word Frequency dialog) and you have the Whole Word box checked in the S&R dialog, then it reports the number of times the word appears in the WF list. This is the old historic feature that predates all the "Count" functions - you don't need to press a button for it, it just updates automatically in the dialog when you have Whole Word and the WF list has been generated. Also note, I don't think it's guaranteed that WF's idea of a word is necessarily identical to the regex-based "Whole Word" flag in the S/R dialog.

The Quick Count of highlighted text from the main window forces whole word searching, so could give different results to the other two if they don't have Whole Word enabled. Perhaps its title bar should say Word Count to clarify that?

**Comment by charliehoward4dp** [comment]
Good idea: "Word Count" from the main text window and "QS Count" from the Quick Search dialog.

The three counts occasionally give slightly different results, but I'm generally using the two Quick ones to decide whether or not to change a spelling or hyphenation (for consistency), so those small discrepancies don't matter.
