### ISSUE TITLE
pphtml no longer finds .br when unused

### ISSUE THREAD

**Issue by btaylor289** [DistributedProofreaders/guiguts#1240]
Running version 1.6.0 of Guiguts.

I click on HTML/PPhtml and view the report of "CSS possibly not used:" br no longer shows up even when unused.  I have 
run across this three times now after upgrading to the latest version of Guiguts.

The CSS code in my html file is:   .br       {border-right: 2px solid;}

The online version of PPhtml does list br as defined but not used

I've attached a screenshot of both the online and Guiguts outputs showing the difference.
Thanks
Bob

![PPhtml](https://github.com/DistributedProofreaders/guiguts/assets/121249433/d4224ee5-d97c-4d85-90c9-50da06e730ea)

**Comment by windymilla** [comment]
The explanation is that `br` is the name of an HTML element. While this is legal to also use a CSS class name, the changes to the code in pphtml (to avoid previous false positives) stores the elements and class names in the same structure. Therefore since your file contains the element `<br>`, pphtml mistakenly counts that as using `class="br"`.
I'll have a look at the code to see if it can be rewritten to properly distinguish between elements and class names.

**Comment by windymilla** [comment]
@btaylor289 - please could you copy [this version of pphtml](https://www.dropbox.com/scl/fi/qjtc4jb650uzphmzhr7sm/pphtml.pl?rlkey=pysr9xghdjdhx83fy206ww6b1&dl=0) into your `lib/ppvchecks` folder under your Guiguts release, and see if it works as you expect. Thanks

**Comment by btaylor289** [comment]
Hi Nigel,

Yes, this updated pphtml did find the unused .br in my CSS.  One change is the entire list is in reversed order from what I'm used to.  I'm not complaining - I like it in this order.

Thanks
Bob

**Comment by windymilla** [comment]
Oh yes, forgot to mention that I decided to reverse the list while I was fixing the bug

**Comment by windymilla** [comment]
[Updated version](https://www.dropbox.com/scl/fi/qjtc4jb650uzphmzhr7sm/pphtml.pl?rlkey=pysr9xghdjdhx83fy206ww6b1&dl=0)  in case you want it, @btaylor289. Previous version gave spurious report about `x-ebookmaker` classes.

**Comment by btaylor289** [comment]
Got it and it seemed to work just fine.

Thank you Nigel.

Bob
