### ISSUE TITLE
Spell Check=>Change All not restricted to words.

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#1241]
Spell check change all replaces all instances of the characters.  For example, "chearful" is not in the dictionary, "cheerful" is the suggested replacement and the popup indicates that are 2 instances present in the file--the count includes the instances of "chearful" but not the 1 instance of "chearfulness".  Selecting Change All replaced all three occurrences.

**To Reproduce**
1. Open Guiguts
2. Select the word "chearful"
3. Press F7
4. "chearful" is displayed in the not in the dictionary window.  
5. "2 exact in text." is displayed in the header.  [There are 2 occurrences of chearful and one of chearfulness in the project.]
6. "cheerful" is displayed in the Replacement text window.
7. Select "Replace All"
8. All three words containing the sequence "chearful" are replaced with the sequence "cheerful".

**Expected behavior**
"chearfulness" was not included in the count of exact words and therefore should not have been altered.  Only the 2 exact words "chearful" should have been replaced.

**Environment**
Currently Running:
Guiguts, Version: 1.6.0
Platform: MSWin32
Microsoft Windows [Version 10.0.19045.3324]
Perl v5.32.1
Aspell 0.50.3
perl/Tk Version: 804.036
Tk patchLevel: 8.4
Tk libraries: C:/Strawberry/perl/site/lib/Tk

**Additional context**
I had observed the "chearfulness" and intended to rectify it; however, I was astonished to discover that it had been included.

My concern is that the presence of a sequence of characters in a word does not necessarily mean that there is a relation to the word intended to be replaced.  For example, I added the word "heer" and did a spell check with the replacement text suggestion "hear". All instances of "heer" were replaced by Change All thus changing "cheerful" and "cheerfulness" to "chearful" and "chearfulness".

**Comment by windymilla** [comment]
@okrick - Not much consolation, but Guiguts has "always"  (i.e. last 10 years) done this.

The issue doesn't occur when using the recently added Spell Query tool (since it doesn't have a Replace All button).

I suspect the reason this hasn't been reported previously is that PPers often don't "correct" spellings that occur several times in a project, because the thinking is that the original intention/spelling should be preserved. I suppose an exception could be if "cheerful" occurs lots of times, but "chearful" just twice, in which case the PPer might be regularising them. 

One difficulty in fixing this ancient piece of code is that Aspell's idea of a "word" may not be the same as Guiguts' idea, for example, are the following single words? Words with hyphens, words with straight apostrophe, words with curly apostrophe, etc. Since the Windows version of Aspell doesn't cope well with Unicode characters, there may be difficulties with accented characters mid-word too. Spell Query's idea of a word, is a sequence of alphanumeric, apostrophe or "mark" characters, but I'm pretty sure Aspell (and therefore Spell Check) is different.

Two possibilities: 
1. Don't use Change All in the Spell Check dialog (and we could consider removing the button and/or documenting its dangers in the manual)
2. I could make some kind of fix to only replace words if they are bounded by "word boundaries" (i.e. `\b` in a regex, which is what Guiguts' own "Whole Word" Search & Replace does

**Comment by okrick** [comment]
Removing the Change All button is probably the best and easiest fix. I hardly ever use it.  I was making the change because cheerful does occur many times and chearful only twice or three times depending on how one counts.
