### ISSUE TITLE
Latin-1 ISO 8859-1 menu no longer inserts characters into the search & replace menu

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#140]
Latin-1 ISO 8859-1 menu no longer inserts characters into the search & replace menu. 

**To Reproduce**
1. Open Guiguts
2. Open the Search & Replace menu ...
3. Position the cursor in any replace field
4. Open the Tools-->Character Tools-->Latin-1  menu ...
5. Click any character in the Latin-1 ISO 8859-1 menu
6. The character is inserted into the document instead of in the Search & Replace menu Replace section

**Expected behavior**
In Guiguts 1.0.25 the character is always inserted into the Search & Replace menu when the cursor was in the Search & Replace menu immediately before clicking the character.  Obviously it the cursor was in the document area immediately before then the character would be inserted at that location in the document.

**Environment**
* Guiguts version: 1.1.0 beta 1
* OS and version: Windows 10 Home 1909 18363.959
* Perl version:  Strawberry Perl (64-bit) 5.30.2.1-64bit
* Perl distribution: perl 5.30.2

**Comment by windymilla** [comment]
In my testing, it works in all the replace fields that were visible when the dialog was popped. It only doesn't work if you use the "+" sign to add another replace field. If you then close and reopen the dialog it works in the new field too.

**Comment by windymilla** [comment]
The original "Reproduce" steps don't work in 1.0.25 either. It is necessary to add a step after Step 4.
4b. Position the cursor back in a replace field.

With that step, it now works in 1.0.25. 
The same steps also work in 1.1.0 (same environment)

There is a way to make it fail. You need to use the "+" sign to add another replace field and try to insert Latin-1 character into the new field.

To Reproduce
Steps to reproduce the behavior:

1. Open Guiguts
2. Open the Tools-->Character Tools-->Latin-1 menu ...
3. Open the Search & Replace menu ...
4. Use the "+" to add another replace field
5. Position the cursor in the new replace field
6. Click any character in the Latin-1 ISO 8859-1 menu
The character is inserted into the document (or previously focused replace field) instead of in the new replace field.
