### ISSUE TITLE
Search & Replace immediately replaces selected text before search

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#180]
To limit a Search & Replace one must select a block of text.  If Replace, R & S, or Repl. All is clicked next then the selected text is replaced with the literal replacement expression.  If a block of text is not selected first then clicking the R & S or Repl. All buttons initiate a Search before any replacement is done.

**To Reproduce**
1. Open Guiguts
2. Open the Search-->Search & Replace.... menu
3. Enter a regex function in the Search field, e.g. (?<=,” )(\d{1,3})\b|(?<=, )(\d{1,3})\b
4. Enter a regex function in the replace field, e.g. #$1#
5. Click the Regex selector
6. Select a block of text that only needs the specific Search & Replace
7. Click either the Replace, R & S, or Repl. All buttons.
8. The selected block of text is replaced with the literal replace expression, e.g. #$1#

**Expected behavior**
If the R & S button is clicked, then I expect the next item matching the search regex would be found, and no replacement would happen until the R & S is again clicked.  This is the behavior that occurs if no text block was selected.

If the Repl. All button is clicked then I expect the next item matching the search regex would be found and replaced and that replacing would continue until all items matching the search are found and replaced.  This is the behavior that occurs if no text block was selected.

If the Replace button is clicked, then I expect either that nothing would happen or that the next item matching the search regex would be found and no replacement would happen.  If no text had been selected then the literal replacement expression is pasted at the cursor location--I feel this is also a bug.  Do you need a separate bug report?

**Environment**
* Guiguts version: 1.1.0
* OS and version: Windows 10 Home 64 bit 1909
* Perl version: Strawberry Perl (64-bit) 5.30.2.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.2.1-64bit

**Comment by windymilla** [comment]
I have a virtually identical setup, but when I follow the steps to reproduce, the behaviour is as expected.
Can you try following your steps exactly again and see if there's some other step needed, please? If it still goes wrong for you, could you add more detail, specifically about how you switch from the main window to S&R dialog and back - are you using the menu, or Ctrl-F, or clicking with the mouse, etc. Please note every click or keystroke even if it doesn't seem important.

It is possible to get results like you describe (depending on exact circumstances) with something like the following (incorrect) steps:
1. Open the S&R dialog
2. Enter a search string
3. Return to the main window and select some text
4. Use Ctrl-F to go back to the S&R dialog (this is the step that is wrong, because it changes the search string to be the selected text - you are starting a new search based on the selected text)
5. Click Replace All (maybe need to click Start at beginning first)

**Comment by okrick** [comment]
Odd. I was able to duplicate my steps three times the day I entered this.  I agree that Ctrl-F to reopen the window does enter the selected text as a search string.

It still isn't correct though.

1. Close the S&R dialog (so nothing is highlighted)
2. Open the S&R dialog
3.  Enter a search string
4. Return to the main window and select some text
5. Use alt-tab to return to the S&R dialog (unnecessary if the S&R window is off to the side)
6. Click S & R

The next matching string after the cursor position from when the S&R dialog was opened is selected--it should be the first string **within** the selected text.

**Comment by windymilla** [comment]
No problem - I do appreciate that you report bugs or request features - it helps me to get a feel of what things are annoying to people using GG

**Comment by okrick** [comment]
I had noticed that there were a lot of places in my current project where the text was replaced with the literal replacement text.  This was with search and replace expressions that I've used for years.  I was trying to figure out what had happened.  It was mostly when I clicked R & S but sometimes with Repl. All.  I restarted the project and so far I haven't found what went wrong.  Still looking.
