### ISSUE TITLE
Remove kindlegen binary and point people to KindlePreviewer

### ISSUE THREAD

**Issue by cpeel** [DistributedProofreaders/guiguts#208]
Frustratingly, Amazon pulled the stand-alone [kindlegen download](https://smile.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211&sa-no-redirect=1) and instead are pointing people to [KindlePreviewer](https://smile.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261&sa-no-redirect=1). This breaks packaging for Windows and Macs. The Previewer includes kindlegen somewhere in it, but the Previewer is an installation executable and we can't extract the binary for packaging.

We should stop trying to package kindlegen in GG and instead point people to download and install KindlePreviewer. We can make this slightly less painful by adding the (presumptive) kindlegen path to the GG batch file.

**Comment by windymilla** [comment]
Ebookmaker uses Calibre for conversion in languages not supported by kindlegen. So it may be more appropriate to point people to Calibre - many will already have it installed anyway.

Should be able to provide [a config file](https://github.com/gutenbergtools/ebookmaker/blob/ca9025dff9ff8a82a41be6325edc713b05f67804/ebookmaker.conf) to ebookmaker with the `--config=filename` option.
Maybe just needs to contain the line
`mobigen: ebook-convert`

The Calibre install contains the program [ebook-convert](https://manual.calibre-ebook.com/generated/en/ebook-convert.html) which is on the Windows path.

**Comment by windymilla** [comment]
It is important that the GG conversion process matches the online one when users upload to https://ebookmaker.pglaf.org/
At present, this may mean continuing to supply the kindlegen executable rather than what is contained in KindlePreviewer.
If providing a way to utilise the Calibre method built into ebookmaker, it would need to be optional and default to "off" until/unless the online ebookmaker process uses Calibre by default.

**Comment by tangledhelix** [comment]
I wanted to mention another reason to stop distributing the kindlegen Mac binary: it's 32-bit, so it won't run on Catalina or Big Sur, which both require 64-bit only.

```
% ./kindlegen
zsh: bad CPU type in executable: ./kindlegen
```

**Comment by windymilla** [comment]
1. Add kindlegen location to the Prefs->Set File Paths dialog
2. Default location should ideally be where Kindle Previewer installs kindlegen by default - this may not be possible/easy since default kindlegen location is `C:\Users\myusername\AppData\Local\Amazon\Kindle Previewer 3\lib\fc\bin`
3. Make creation of the mobi file dependent on availability of kindlegen, i.e. if kindlegen not found at location set in Prefs, don't tell ebookmaker to create it. If not found, issue information message when running ebookmaker explaining why mobi is not being created and direct user to install Kindle Previewer and use Prefs to locate kindlegen in the lib\fc\bin subfolder of the Kindle Previewer installation folder.
4. If creating mobi version, add location defined in Prefs to path when spawning ebookmaker process, so ebookmaker can find kindlegen.

**Comment by charliehoward4dp** [comment]
Letting people select the location of kindlegen.exe on the Prefs->Set File Paths dialog is a long-term, easy solution to this issue. Since all previous versions of Guiguts included kindlegen.exe, people who don't want to install Kindle Previewer 3 can point to a kindlegen.exe that's in an earlier version of Guiguts. If they think they might someday delete older versions of Guiguts, they can put a copy of one of those kindlegen.exe's in some other, permanent folder, and point to it.  All the kindlegen.exe's, including the one bundled with KP3, generate what appear to be identical .mobi's.
