### ISSUE TITLE
F1 help key for Compose dialog goes to wrong manual page

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#411]
**Describe the bug**
Make the F1 help for the Compose dialog point to 
https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_1.1_Manual/Guiguts_1.1_Help_Menu#Compose_Sequences

**Comment by charliehoward4dp** [comment]
There is no specific ID for "Compose sequences" on any page of the manual, but letting F1 for that dialog link to the Help Menu's manual page (https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_1.1_Manual/Guiguts_1.1_Help_Menu) will work fine, because the explanation is quite near the top of that page and includes an image of the dialog.

**Comment by windymilla** [comment]
Thanks Charlie - I think I've got it now 👍
