### ISSUE TITLE
Add px option in parallel with em and % for HTML Images

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#444]
**Describe the solution you'd like**
When adding an illo with the Image dialog, the user currently has the option of the image size being specified by percentage or in ems. Add a third option to specify in pixels.

**Comment by tomcosnj** [comment]
Thanks for adding the option for PX.

However, I think if the user enables the use of PX, it implies that they would prefer that to be the default selection on the Image dialog.

So, can the an enhancement be done so that if the user enables the use of pixels in the Image dialog that the default geometry be set to px?
