### ISSUE TITLE
Double click error message

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#494]
**Describe the bug**
08:12:11: Guiguts 1.2.4-beta: If you have any problems, please include any error messages that appear here with your bug report.
10:42:54: Tk::Error: Usage $widget->place(...) at C:/Strawberry/perl/site/lib/Tk/Widget.pm line 1198.
 at C:/DP/guiguts/lib/Guiguts/LineNumberText.pm line 107.
 Tk::After::repeat at C:/Strawberry/perl/site/lib/Tk/After.pm line 80
 [repeat,[{},undef,300000,repeat,[\&Guiguts::Preferences::__ANON__]]]
 ("after" script)

**To Reproduce**
1. Open Guiguts
2. Double clicked on 'nationalites' in line 24125
3. See error

**Expected behavior**
I expected the word to be highlighted only.

**Environment**
* Guiguts version: 1.2.4-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Files**
[psychopathia.zip](https://github.com/DistributedProofreaders/guiguts/files/5895696/psychopathia.zip)
FYI psychopathia.txt disappeared.  yi9zSScSfI seems to be the same file but I included the last .bk1

**Comment by okrick** [comment]
There is more. I can't save the file:

![Capture](https://user-images.githubusercontent.com/17208131/106316021-f3947380-6220-11eb-9d0e-81d9b27db2b2.JPG)

08:12:11: Guiguts 1.2.4-beta: If you have any problems, please include any error messages that appear here with your bug report.
10:42:54: Tk::Error: Usage $widget->place(...) at C:/Strawberry/perl/site/lib/Tk/Widget.pm line 1198.
 at C:/DP/guiguts/lib/Guiguts/LineNumberText.pm line 107.
 Tk::After::repeat at C:/Strawberry/perl/site/lib/Tk/After.pm line 80
 [repeat,[{},undef,300000,repeat,[\&Guiguts::Preferences::__ANON__]]]
 ("after" script)
10:44:25: Use of uninitialized value $mode in bitwise and (&) at C:/DP/guiguts/lib/Guiguts/FileMenu.pm line 436.
10:45:08: Use of uninitialized value $mode in bitwise and (&) at C:/DP/guiguts/lib/Guiguts/FileMenu.pm line 436.
10:45:13: Tk::Error: Usage $widget->place(...) at C:/Strawberry/perl/site/lib/Tk/Widget.pm line 1198.
 at C:/DP/guiguts/lib/Guiguts/LineNumberText.pm line 107.
 <Control-Key-s>
 (command bound to event)

Clicking "Yes" gives the same popup and repeats the error message.  "No" returns me to the file but I'm stuck.  I'm going to revert to the last bk1 to continue.

**Comment by windymilla** [comment]
OK - here's my best understanding - it might not be perfect.
1. I don't think it's anything to do with double clicking that word.
2. Looking at the traceback error messages, I'm pretty sure it tried to do an autosave (I assume you have that turned on) at about the time you did the double click, which is why you though the double click had caused it.
3. It seems the autosave failed, possibly halfway through writing the file -  the "yi9zSScSfI" file you included is only the first part of the file, not the whole thing, unlike the bk1 file.
4. I can't work out the reason for the failure (potentially a disk problem?)
5. The later errors you report "Use of uninitialized value $mode..." are only possible if GG fails to get information on a saved file - this should never really fail, so again points to a problem either with that specific file or possibly the area of disk it is on.
6. If you have the capability to perform a disk check, I would do that.
7. If you are ever in the same situation again, instead of trying to save the file, try to do Save As and give the file a new name, like psychopathia2.txt

As you will realise from the above, I can't regenerate the error at all with the files you sent. I hope your problem will turn out to  just be an unlucky one-off failure or perhaps a disk issue that is rectified by "checking" it.

**Comment by okrick** [comment]
I ran both the Dell and Microsoft checks on my SSD.  It passed both.  So this is probably FM.

Thanks for checking it and for the Save As tip.  

This can be closed.  It can be reopened if it pops up again.

**Comment by windymilla** [comment]
Closing as agreed with @okrick 
If similar occurs during autosaving, it may be necessary to restrict when autosaves are permitted to happen, e.g. if program has been idle for a short time. Also check/consider if program should be made "busy" during actual autosave so that user does not start an operation, even one as innocuous as double clicking a word, during the autosave.
