### ISSUE TITLE
Restore S&R default width to '50' instead of the new '40'

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#510]
In the latest version, when the S&R dialog opens, it is significantly narrower than in it was in earlier versions, including 1.1.1 and going back at least to 1.0.24. The reason for this is that four 'width' values in SearchReplaceMenu.pm were changed to '40'. Changing them to '50' closely matches the historical default width.

If there are other reasons for the change, perhaps yet another 'Preferences' option could be added; but (IMO) it would be a lot easier to just change the constants.

**Comment by okrick** [comment]
Please do not change it back to 50.  A width of 50 means the S&R box is more than a half screen width when I set the font size to the same size as the main window.  I had to use the super tiny system default for the buttons on the right to not be covered by the image.

**Comment by charliehoward4dp** [comment]
Strange. Here are my monitor's measurements and settings:

27" desktop monitor, set at 1920x1080. The screen is 23.5" wide

Guiguts Font settings:
   Main window: Courier New, 12point bold
   Unicode/Greek: DP Sans Mono, 16point not bold
   Text entry: Courier New, 10point not bold
       "use system default for text entry fields" checkbox is NOT checked.

With those values, and with the distributed S&R width of "40" in SearchReplaceMenu.pm, the S&R box is 5.6" wide when it appears.  That's just under 25% of the screen's width, and I almost always have to made it wider to see enough of the search strings to know what they are.  With the internal width set at "50", the box is just under 7" wide. (In GG 1.0.25, it is 7.25" wide, and that's the distribution default.)  For reference purposes, the main GG window is just over 9" wide when it can just barely display the entire toolbar.

**Comment by windymilla** [comment]
For comparison...

The laptop I use has a 14" screen, resolution 1920x1080, width about 12" and height 6.5" (I wish I had more width and height, especially when I'm coding)

Main window: DP Sans Mono, 10pt
Unicode: DP Sans Mono, 10pt
Text entry: Courier New, 11pt (system default NOT checked)

At width "40", the S&R box is 5" wide, which is just over 40% of the screen's width. At width "50", it would be about 6" or 50% width. (In GG 1.1.1, it is about 5.5" wide). The main GG window is just over 7" wide when it can just barely display the entire toolbar and has space for 72 character width (no line numbers), so about 10 characters per inch. I don't have any vision issues that require me to use a large font, just the small screen.

If possible, I would like to make the box resizable and retain its size. Other dialogs can do that - the issue here is that the height cannot be set in the usual way because it needs to grow/shrink depending on how many Replace lines you have showing. I suspect this is why the code was written in that way, with the fixed entry field width. I'm sure it should be possible to do what we want, but it's too risky a job to do in the 1.2.* releases.

**Comment by okrick** [comment]
The Word Frequency popup is freely moveable and resizable. It also remembers where it was between projects and when closing and opening Guiguts.

Why not make the Search and Replace popup freely movable and sizeable?  And have it remember where it was the last time it was used.  Setting it to a fixed 40 or 50 character width creates problems for users depending on what they prefer.

I don't mind if part of either search or the replace field is hidden as long as I can easily read the text that is present.  I can always scroll to see the rest.  But I can understand why others might find that inconvenient.  I was finding it inconvenient when I had to repeatedly rescue the S&R buttons from under the image when auto-image is used.  Having an S&R popup with a memory of size & placement should satisfy most users.

**Comment by windymilla** [comment]
I'm going to close this request as it is essentially a bug that the width is not preserved. Fixing that would please everyone I think. The bug was already reported by #460

**Comment by windymilla** [comment]
I've noted already the reasons for not doing that in a minor release, but #460 covers the plan to do a proper job on it for the next release.
