### ISSUE TITLE
Provide a straight quote to curly quote conversion tool

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#520]
**Describe the solution you'd like**
Ideally, the same algorithm used by ppsmq should be included within Guiguts. The results could be presented in several ways, e.g. an error list like Bookloupe produces, or a set of coloured tags like Footnote Fixup, or the "@" character method used by ppsmq.

An advantage of the "@" character method is that it is semi-permanent, i.e. if the user quits the program part way through the checks and then returns to it later, the potential issues will still be flagged - this would be hard to do with the other methods, since the flags don't necessarily mean errors, just something that requires human checking.

A dialog to help with fixing the flagged quotes might be useful, or maybe configure the S&R dialog to have several rows with the potential replacements for the flagged quote, and the user would just click on the appropriate Repl & Search button.

**Comment by cpeel** [comment]
For reference: `ppsqm.py` is available in the [ppwb repo](https://github.com/DistributedProofreaders/ppwb/blob/master/bin/ppsmq.py)

**Comment by charliehoward4dp** [comment]
Here are two sets of test files (each set containing a pre- and post-curly, with .bins), .txt only, as I use ppsmq just before the txt/html fork and never have used it after HTML Generate.  If you want to test with HTML, you could run the precurly files through AutoGenerate and run the output through your ppsmq.

"precurly" is input to ppsmq and "curly" is the uncorrected output of ppsmq.  Both output sets have @ flags for a variety of reasons, including ditto marks, multi-paragraph quotations, and multi-line signatures. Both have uncurled single quotes at the beginning of a word.

Offering correction buttons would be a nice touch, particularly if they removed the @ as well as changing or keeping the questionable quotation mark.

Although the suggested approach of making the result match current ppsmq's makes sense because it'll confirm the code works properly, there are at least three safe improvements to consider: a double-quote at the beginning of a line must be an opening quote; a double-quote at the end of a line must be a closing quote; and a doube-quote surrounded by at least two blank spaces must be a ditto mark. Handling these also should reset what the code expects the next double-quote to be. A compromise might be to exactly match ppsmq for now, and make the improvements later, or to add [yet another] option in a menu.

[curlytestfiles.zip](https://github.com/DistributedProofreaders/guiguts/files/6119714/curlytestfiles.zip)
