### ISSUE TITLE
Infinite loop error

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#544]
**Describe the bug**
I tried to find Unicode characters beginning with "Four dot".

**To Reproduce**
1. Open Guiguts
2. Open the Tools=>Character Tools=>Unicode Character Search"
3. Type the text "Four dot" into the box
4. A three-line repeating error message starts scrolling
5. See the error image.

**Expected behavior**
I expected a list with FOUR DOT PUNCTUATION and FOUR DOT MARK plus others.

**Environment**
* Guiguts version:  1.2.4
* OS and version: Windows 10 Home 20H2 64bit
* Perl version: Strawberry Perl (64-bit) 5.32.1.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.32.1.1-64bit

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17208131/108558628-098cd580-72af-11eb-89be-20edcd2392d6.JPG)

**Additional context**
I restarted the PC and it still happens even with no file loaded.

**Comment by windymilla** [comment]
Have you only noticed this since upgrading to Strawberry Perl 5.32? And are you pretty sure it was working recently.
I have the same issue - it seems to go wrong whatever search you do - it's not specific to "Four dot". It's also showing in release 1.1.1, which I'm sure would have been reported before now if it had been the case since back then. There may be a change in the format of the list of unicode characters which is bundled with Perl.
I'll look into it further. 
If you can face it, you could try uninstalling 5.32 and reverting to 5.30. However, I know that means re-running the cpan installation of Perl modules so it takes a bit of time, so I wouldn't blame you for not wanting to.

**Comment by windymilla** [comment]
Update: Guiguts has always depended on a file under the Perl installation called lib/unicore/Name.pl
It used to have a comment saying "!!! DO NOT EDIT THIS FILE !!!" and consisted of a list of unicode ordinals and character names, e.g. 
`2A78		EQUIVALENT WITH FOUR DOTS ABOVE`
However, now the file says
```
# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.
```
And sure enough, the format has changed

There's a link [here](https://rt.cpan.org/Public/Bug/Display.html?id=132471) with some info on how to get the list of names via an approved method.

**Comment by okrick** [comment]
So that was the issue.  I can revert to the old Strawberry.  I did that for the reinstallation of guiprep.

**Comment by windymilla** [comment]
Thanks - apologies for the inconvenience. I'll look into what to do about it.
