### ISSUE TITLE
Tools>Footnote Fixup: Missing opening '[' of footnotes not detected explicitly by First Pass

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#603]
**Describe the bug**
When the opening '[' of a footnote is missing, First Pass does not flag this. However the 'count' of footnotes (the number of the last one in the list) displayed by the First Pass report will be less than it should be and, additionally but not surprisingly, the footnote anchors after the incorrect footnote's no longer correspond in the First Pass report to the correct footnotes.

If the expected number of footnotes is not checked by the user against the number detected by First Pass, then a 'lost' footnote can cause unexpected behaviour when moving to LZs or reindexing.

This seems to be a long-standing problem because the 1.2.4 GG Manual warns about it in the **Inspect Footnotes** subsection of the Footnote Fixup section, saying
> Do not go on to further steps until there are no errors shown in the Check Footnotes report and you have verified the length and anchor of all notes. (As a veteran of multiple books having several hundred footnotes each, this writer can testify that there is simply no substitute for inspecting each footnote in sequence. Footnote syntax is complex and prone to subtle errors. Not all errors are displayed in the Check Footnotes report. You simply must verify proper scoping of every note. Any uncaught errors will cause chaos later on.)

The Footnote Fixup menu does give you the means to inspect each footnote and its anchor in turn with the Prev. FN and Next FN buttons. 

The advice above perhaps needs to be brought to the attention of users of the Footnote Fixup tool each time s/he uses it? See also comment in Expected Behavior section below.

**To Reproduce**
1. Open Guiguts with [footnote-fixup-test-V3.txt](https://github.com/DistributedProofreaders/guiguts/files/6097464/footnote-fixup-test-V3.txt)
2. Edit a footnote to remove the opening '[' bracket.
3. Open the Footnote Fixup menu and click First Pass.
3. Check the number of the last footnote in its report against the expected count of footnotes.
4. Try moving footnotes now to, say, Chapter LZ, and see what happens. Also an attempt to Reindex will give incorrect results.

**Expected behavior**
I would expect a missing '[' to be detected (but this might be very difficult to do) _or_ at least a warning that the number of (syntactically correct) footnotes in the First Pass report does not appear to agree with the count of 'Footnote: ' strings in the text just processed. This latter count should be a by-product of the scanning done by the tool.

**Environment**
* Guiguts version: 1.3_210304
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**
N/A

**Additional context**

**Comment by windymilla** [comment]
I'm not convinced that First Pass should detect strings that are not exactly `[Footnote:`, for a couple of reasons. One is the question of where do you stop? What if the colon was a semicolon, or Footnote was misspelled? Actually a couple of these are already detected and silently corrected, e.g. `[Fotonote`, `[ Footnote`, `[ footnote` and `{Footnote`.
Certainly, it would be dangerous to silently correct `Footnote: ` to `[Footnote: `, since it could just be part of the text, not footnote markup at all.
I will add a warning if the number of `Footnote:` strings does not match the number of footnotes at the end of First Pass. I think that is a reasonable compromise, and alerts the user that they need to check something.
