### ISSUE TITLE
Problem with Search & Replace - intermittent and probably related to UTF-8 characters

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#629]
**Describe the bug**
If I use Rpl All in Search & Replace to change opening curly double quote [“] mark to straight double quote marks ["] throughout the file that was converted as in Bug report #628, the Rpl All sometimes works and sometimes doesn't. 

It appears to be related to UTF-8 characters. See comment in 'Additional context' section below.

On the occasions when it doesn't work the bell sounds when Rpl All button is clicked. Message boxes flash up momentarily and the Guiguts window appears to shudder and contract then restores itself. The opening curly quote marks are not replaced. There are no messages logged in the cmd.exe window.

If, after the above occurs, I click Rpl All again, then the replacement occurs without further issues.

When it works on the first use of Rpl All, it appears to go as expected. No bell sound, no message boxes and all [“] are converted to ["].

**To Reproduce**
1. Open Guiguts with [curly-quotes.html](https://github.com/DistributedProofreaders/guiguts/files/6143760/curly-quotes.zip)
2. Open Txt>Covert to Curly Quotes...
3. Open Search & Replace and try replacing [“] (say) with a straight quote using Rpl All.
4. See error behaviour described above when it occurs. However the error behaviour is intermittent.

**Expected behavior**
Expected behaviour is obvious.

**Environment**
* Guiguts version: 
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
Have done some further testing. This problem appears to be related to attempts to change UTF-8 characters only with Rpl All. If I open and edit the unconverted curly-quotes.html file and attempt to replace the single UTF-8 apostrophe (Dec 8217/Hex 2019) in the title text with a straight single quote using Rpl All, the intermittent error described above can occur.

The bug occurs whether using Rpl All to  replace a UTF-8 character with an ASCII one or vice versa.

**Comment by windymilla** [comment]
I can't reproduce this as described. It is possible that what you are seeing is actually expected behaviour - see below.

When GG starts a Repl All, it hides linenumbers (and replaces them at the end) to speed up display updating when lots of replacements are done. Also, it pops a "busy" dialog to tell the user it is busy. If GG is then unable to find the string, it will sound the bell.

This seems to be what you describe as "shudder/contract" (linenumber hide & restore), "message boxes" (busy dialog), and bell. So, I believe GG is saying it can't find the string you are searching for.

One reason for that would be if you had a selected region in the main window when you did the Repl All, because then it would only search in the selected region. That can happen if you selected some text to copy/paste it into the S&R dialog and then clicked S&R.

Try these two operations:
1. Get a curly quote in your copy/paste buffer, e.g. by selecting it from your file.
2. Open S&R dialog
3. Paste the curly in the search box
4. Type straight quote in the replace box
5. Single click in the main window to make sure you don't have any text selected
6. Click Repl All

And:
Same as above apart from step 5
5. Select a straight quote from near the word 'here' so it is highlighted blue - no need to copy/paste it
6. Click Repl All

For me, the first set of operations works and the second behaves like your description. If that seems to explain it, this could be closed. If you are getting the bell when you have nothing selected in the main window, that would indicate a problem.

**Comment by G4OEU** [comment]
It appears to be as you suggest above. However it occurs when it is not obvious that you have text selected (nothing highlighted in blue). This can happen when the S&R dialog box is already open. 

CTRL+C to select the apostrophe in the title text. Click in the Search Text box of the _already open_ S&R dialog. CTRL+V to paste the apostrophe there. This clears the blue highlighting in the main window but the character is obviously still selected because when you then click Rpl All, you get the 'cannot find' behaviour described. But since the 'selected region' is the character it is searching for (apostrophe) I am unclear why it can't find it.

**Comment by G4OEU** [comment]
On further investigation, the way in which S&R searches seems consistent with how Rpl All behaved as described in my previous comment. Will close this issue.
