### ISSUE TITLE
Separate with a line EbookMaker from the text above it. Rename it to "EbookMaker creation"

### ISSUE THREAD

**Issue by rpajbox** [DistributedProofreaders/guiguts#631]
As it stands now, in the HTML menu, EbookMaker is the last of a set of tests. But EbookMaker is not really a test, but a software build, which ends without any output (it is even difficult to find where the built product has been placed).

I suggest to separate EbookMaker from the items above it in the menu (all of them tests) with a line, and rename it as Ebookmaker creation or production or generation (or the best English noun for this process).

And it would be great that, after EbookMaker has finished, a window would open to tell the user that two files have been created, with the extensions .epub and .mobi, and in which directory they are to be found.

Thanks for considering this suggestion.

**Comment by windymilla** [comment]
#### Already done

- I have changed for the next release that Ebookmaker creation will show the "busy" cursor until it finishes - so now you know when the process is finished.
- If it generates errors, it will pop up the error message box with them in when it is done.
- If there are no errors, it will still write messages to the message log, but won't pop it up - you can always go and look at the Message Log from the Help menu when the busy cursor goes away if you want to see the messages.

#### Will do

- Add separator line to menu
- Rename "Ebookmaker" option to "Ebookmaker epub/mobi Generation"

#### Won't do
- Open a Window to say what the files are called and where they are. The reason for not doing this is that there are already two ways to know this information: since the files are always created in the same folder as the file you are editing, and always have the epub and mobi filename extensions, so they shoudl be easy to find. The second way is to pop the Message Log from the help menu if it doesn't pop up because of an error, and you can see near end of the messages that are output where the files are and the file names, e.g. 
```
INFO:root:Creating Kindle file: C:\DP\misc\ppsmq\curly-quotes2\A Southern Woman_s Story-images-kindle.mobi
INFO:root:            ... from: C:\DP\misc\ppsmq\curly-quotes2\A Southern Woman_s Story-images-epub.epub
```

**Comment by rpajbox** [comment]
Wow!, Nigel. Thanks a lot.
