### ISSUE TITLE
Compose key loses the first typed in character

### ISSUE THREAD

**Issue by rpajbox** [DistributedProofreaders/guiguts#654]
I consistently observe that whenever I use the Compose Key window, the first character I type in this window is lost. I must type it in twice to be accepted. This seems not to be as designed.

I am on Windows 10.

Note: My Windows keyboard layout is Spanish. As AltGr is used for several things in this layout I changed (via  Preferences > Processing > Set Compose Key) the default activating key to F10. I hope this has nothing to do with the deviant behaviour I experience with the main Compose Key window.

**Comment by windymilla** [comment]
It may be related to the choice of key, since according to Wikipedia on Windows "F10 generally activates the menu bar". So it might be that Windows is grabbing that first character. Can you try allocating the Compose Key to something like Control+m as an experiment to see if that fixes the problem. If it does, then you could try out some other keys to find one that you find convenient. If it still goes wrong with Control+m, then we'll need to investigate further. Thanks

**Comment by rpajbox** [comment]
You were right (as usual): Changing Compose Key to Control-m does not lose any keypress. I have left it a F9 and it still behaves as it should. Thank you for your insightful suggestion. For my part this issue is closed (but I don't dare to close it myself, being unaware of the consequences).

**Comment by windymilla** [comment]
Thanks - if you hadn't included the detail, e.g. that you had use F10, I wouldn't have thought of it.
I'll close this, and ask Charlie if he would like to put a warning in the manual.
