### ISSUE TITLE
Rewrap All appears confused about /$ ...  $/ bracketing

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#662]
**Describe the bug**
Tools->Rewrap All is failing to honour at least one pair of /$ ... $/ brackets

**To Reproduce**
1. Open Guiguts with [army_recipes.txt](https://github.com/DistributedProofreaders/guiguts/files/6222777/army_recipes.txt)
2. Tools->Rewrap All
3. Scroll down to line 181 'SOUPS.'
4. See error in which some text is wrapped just before a terminating $/

**Expected behavior**
Obvious.

**Environment**
* Guiguts version: 1.3-beta-test2
* OS and version: 
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
Tools->Check Orphaned Brackets does not find any issues

Same error behaviour seen in 1.2.4

**Comment by windymilla** [comment]
There's good news and bad news: it does go wrong, but it also did in every release back to and including 1.0.25, so it's "not urgent"

**Comment by windymilla** [comment]
More good news and bad news: according to [the manual](https://www.pgdp.net/wiki/PPTools/Guiguts/Guiguts_Manual/Tools_Menu#Rewrapping)

> Note:The opening and closing markers (/*, etc.) should stand alone on a line, but these markups must be preceded and followed by blank lines. If the blank lines are missing, Guiguts will fail to recognize either the beginning or the end of the markup and mis-wrapping will result.

Your example file that goes wrong is due to the fact that you have
```
        Tapioca                                              30
$/
/$
    SAUCE:
```
Your close and re-open block markup should have a blank line in-between. 

I'll keep working on a possible fix to allow this case through unharmed :)
