### ISSUE TITLE
Footnote mismatch error message

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#678]
**Describe the bug**
A Footnote Mismatch error appears _every single time_ the Footnote Fixup First Pass is run and locks GuiGuts completely until the OK button is pressed.  Every single time.

**To Reproduce**
1. Open Guiguts
2. Open the Tools=>Footnote Fixup menu ...
3. Click First Pass
5. Press OK
6. Correct some footnotes
7. Click First Pass
8. See error
9. Repeat over and over....

**Expected behavior**
I do not want to see a redundant message (especially not one which locks down GuiGuts).  I do want to see the footnote screen which has the same information in more detail immediately after pressing First Pass.  

Even worse the error appears every single time.  The manual says it appears only the first time which would still be obnoxious.  In fact, I don't ever want to get a message which locks down Guiguts unless there is a danger of corrupting my project file.  

My preference is that this "feature" be permanently removed.

**Environment**
* Guiguts version:  1.3.0-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.32.1.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.32.1.1-64bit

**Screenshots**
![](https://www.pgdp.net/wiki/File:Gg-1.3-33f-footnote_fixup_mismatch.png)

**Additional context**
Alternatively, can this option be turned off permanently in the preferences?  I'm running First Pass dozens of times on projects with hundreds or thousands of footnotes.

**Comment by windymilla** [comment]
I know it does not happen every single time (with or without italics) because I have files where it does not happen.

Unless the feature has a bug in it, it is warning you about something you need to know about. First Pass has failed to capture all occurrences of things that might be footnotes, because some of them are marked up incorrectly, e.g.
Footnote 3:...
instead of 
[Footnote 3:...
If that is the case, you probably need to know about and fix it very early on before you end up with all the footnotes mismatched or wrongly numbered, because that can be a pain to fix later. So, yes there is a danger of corrupting your project unless you fix the issue.

If you think you have a file that does not have that type of problem, but it is still giving you the error, please could you upload it, and I will look at it. Of course, if it is a bug, I will try to fix it, but if it is a problem in your file, then Guiguts is warning you to fix it.

**Comment by okrick** [comment]
It is a bug since the error message locks Guiguts and prevents any action until I click the OK button.  This type of action should be reserved for issues like if I continue this action my hard drive will be formatted or the project file will be hopelessly scrambled.

You'll see that the error reappears until the footnote screen gives the all-clear.  There are no issues like the ones you suggested that might not appear on the footnote screen.  The count of the word Footnote is the same as the actual number of footnotes, 2563.  There is a single occurrence of the word footnote in my TN but that can't be the issue since once the footnote screen is cleared the error stops occurring.  Besides, it is the middle of a sentence and in no way resembles a Footnote.

The thing is the footnote handling is one of my favorite features about Guiguts but now if I clear them through an iterative process I will get that message over and over.  I've had other files with thousands of footnotes.  Yes, I've had the exact case you are talking about.  But it would be better to add another column in the footnote screen.  Or just a warning that identifies the type of error and does not lock down Guiguts until cleared.  

[poisons.zip](https://github.com/DistributedProofreaders/guiguts/files/6240296/poisons.zip)

Sorry, if I come across as upset but I feel the footnote handling of Guiguts was seriously crippled by this addition.  This book has a lot of footnotes but it is relatively issue-free in that respect since the proofers kindly pointed out the duplicates in advance.  I was pleasantly surprised that there were only two no-anchors out of over 2000. The one last month took days to work through the footnote issues.  I ran and reran the First Pass probably over a hundred times.  I don't want to see this message that many times.

**Comment by windymilla** [comment]
Point taken, Rick. Having reviewed the behaviour in your file, and the code, it's clear it would be hard/impossible to accurately match all the cases that First Pass interprets, while not counting the word Footnote in the text or TN, but also making it useful enough to catch mistyped footnote markup. I'm therefore removing the whole feature. I considered your suggestion of making it a non-blocking warning, but I think it would be misleading due to the point mentioned above. People might be hunting for something that wasn't there. So, it will be gone in 1.3.1

**Comment by okrick** [comment]
Thank you.

I am sorry.  I overreacted.  In part, it was because I originally concluded it was simply repeating that there was an error on the following screen since it stopped when I corrected the two duplicate anchor issues.

I appreciate the thought.  The test could be implemented in a less threatening manner by including the check within the Footnote Check screen with a line number.  There are several other possible things that can adversely impact footnote processing.  I'll come up with a feature request list.
