### ISSUE TITLE
Count given by S & R of item to be searched for in Stealthos does not accord with number of the item that Search actually found in file

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#727]
**Describe the bug**
Running through en-commn.rc, check 50/69 searches for letter 'm' as a possible mis-scan of 'in'. The count given in top right-hand corner of S & R dialog says 'Found 2 times' but the search finds 6 in the attached file.

**To Reproduce**
1. Open Guiguts with [common.txt](https://github.com/DistributedProofreaders/guiguts/files/6365448/common.txt)
2. Open the Tools>Stealth Scannos menu
3. Scroll down to 'en-commn.rc file'
4. Click on 'Next Stealtho' radio button until check 50/69 is in window. It is a search for the letter 'm' in a particular context
5. The issue/error is that the 'Found 2 times' count provided by the S & R dialog is not in accord with the 6 actual instances found by clicking the 'Search' button in that same dialog

**Expected behavior**
Expected the count given by S & R to be same as number of instances found by repeatedly clicking 'Search' button

**Environment**
* Guiguts version: 1.2.4 to 1.3.1-beta
* OS and version:  Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by G4OEU** [comment]
Am curious as to why the **regex.rc** scannos file displays *no* count at all for its checks.

**Comment by windymilla** [comment]
Here is the explanation - I don't know if you find it satisfactory.

Guiguts has historically maintained a list of the "words" in the file and the number of times each occurs. If you want to see that list, you can by using Word Frequency -> All Words. I think a "word" is considered something surrounded with whitespace. (At least some) punctuation is stripped off the end. 

For many years, if you were doing a "Whole word" search, it has used that list to display the count in the Search dialog. In your case, there are two occurrences of "p. m." so the "m" counts as a word twice. When you do a "Whole word" search, it actually does a regex search with a negative lookbehind and and lookahead to ensure that the preceding and following characters are not Alphanumeric. With this definition, "I'm" is a word, but the "m" in it is not a word. You will see in your file that "I'm" appears three times. There is also an occurrence "a.m." which counts under this definition. "I'm" (3 times) and "a.m." account for the difference you are seeing. To see that is really true, you can try a whole word search for "CHICAGO " (with a space on the end), or for "1913, BY"

This historic count is only shown for Whole Word searches, since those are what is stored, and only if the word list has been generated (by Word Frequency or Stealth Scannos). You can see this if you start GG, and load your file, and do a whole word search for "m" - you won't see a count. Run Word Frequency and continue your search and the Count will appear.

Last year, Charlie suggested I add an explicit Count button to the search dialog. If you use it, it does an actual count by going through the file doing repeated searches so will always match the number of occurrences obtained by searching. It gets the answer of 6 you were expecting for Whole Word "m". However, it only counts when you explicitly tell it to, since it might otherwise slow things down. The old word count value is still displayed as it used to be.

That's everything I know. 

To get what you want, you would have to either:
- change what the word list considers a word to match the regex method (but then you wouldn't find "I'm" as a word which would be undesirable for PPers, I believe
- or change the Whole Word search method in the S&R dialog, which I think would lead to complaints about some things matching/not matching unexpectedly, especially around punctuation
- or stop displaying the word list count and essentially do an virtual press of the Count button every time you search (or replace & search). Maybe it should also happen on Replace and Replace All, (and maybe if you type in the search field and hence change the search string - though a time delay for every character typed would be annoying there, so probably not)

Only the last of those seems a possibility - if you want to try it out, add 
```
                $::lglobal{searchpopcountbutton}->invoke;
```
immediately after
```
                searchtext('');
```
on about line 991 of SearchReplaceMenu.pm

You could also add the same line after the call to replaceall about line 1149, the call to searchtext about 1163 and the call to replace about 1177 if you want to experiment with how that looks. It would need quite a bit of testing on large files with lots of words, since essentially you have to search the whole file counting every time you do a search. If it has an adverse performance effect, it might be necessary to have an "Auto-count" toggle.

In fact, after writing that, I think I might put in such a toggle (defaulting to off) in the Preferences menu. What do you think?

**Comment by G4OEU** [comment]
Nigel,

Your idea of a virtual press of the Count button along the lines you
suggedt would be worth trialling (default OFF).

My main motivation for flagging the issue is an instinctive distrust of a
system that tells me one thing but manual inspection showing it is 'wrong'.

However I could see the different 'contexts' in which the regex found the
letter 'm' so realised that the reason for the discrepancy might be more
complex, and not simply a bug. And so it turns out from your explanation!

It would be desirable to always get a 'true' count of what is being
searched for but I acknowledge there are costs to doing that.

Thanks for the reply and the useful background to how GG works in this area.

I will give the mods you suggested a try tomorrow.

Quentin

**Comment by charliehoward4dp** [comment]
Regex searches that include newlines, especially multiple newlines, can take a L.O.N.G. time, every time, to start (presumably, they are stacking all the occurrences before starting to show any of them to the user). That's why I was silent when Nigel added auto-count only for en-common but not for regex. When I want a regex count during Stealth, I click the "Count" button.

The misleading count on "m" is the only (or almost the only) "error" of that sort when doing Stealch en-common searches, and is information-only; it doesn't change anything. If Nigel's willing to implement it in a different way and there's no noticeable performance penalty, it would be even nicer.

If any of these changes incur a noticeable performance penalty, I hope there will be an option to turn it on (default  to remain "off").  My recollection from when Ramon reported a big slowdown in Word Frequency is that Nigel has a faster computer than some of the rest of us, so he may not notice this kind of change.

**Comment by windymilla** [comment]
Auto-count for en-common wasn't added by me - it's been there for ever I think. 
I've investigated further, and whatever I do (short of rewriting the Word Frequency word list generator) will still leave us with discrepancies. For example, you can pop a Search dialog from the WF dialog with right-click. It might say "2  xyz" in the WF dialog, but Count 6 in the Search dialog, or if you allow WF to set the Count label, it would say 2 in the Search dialog, but then when you click Search it would change to 6.
I also noticed a slight lag in performance when searching a big file for "the" which occurred many times.
I think that given the rare occurrence, and ease with which the user can get a "true" Search-style count, and that it is not possible within reason to get all the numbers agreeing and updated without a performance penalty, it's best to let this one go for now.
