### ISSUE TITLE
Character Encoding in HTMLConvert.pm Should Be Updated

### ISSUE THREAD

**Issue by tomcosnj** [DistributedProofreaders/guiguts#755]
Although the HTML Validator which is packaged with Guiguts does not see it as an error and technically speaking it is not an error, however, the on-line W3C HTML Validator warns that "charset=ascii" may not be widely supported. This encoding is equivalent to "charset=us-ascii" which may be better supported across platforms.

Therefore, the encoding should be updated to produce "charset=us-ascii"

```
    if ( $::lglobal{leave_utf} && ::currentfileisunicode() ) {
        $headertext =~ s/BOOKCHARSET/utf-8/;
     } elsif ( $::lglobal{keep_latin1} && ::currentfileislatin1() ) {
         $headertext =~ s/BOOKCHARSET/iso-8859-1/;
    } else {
         $headertext =~ s/BOOKCHARSET/us-ascii/;
     }
```

**Comment by windymilla** [comment]
Re-opening to note the improvement mentioned in the comment above.

**Comment by cpeel** [comment]
I think your overall logic is sound, but I think UTF-8 would be a better option for ASCII-only documents than ISO-8859-1. Because while the latter is indeed the default encoding for HTML4 (which I know is what Guiguts currently exports), UTF-8 is the default encoding for HTML5 which is certainly the future direction and has been around since 2014.

I'm fine with whatever you decide, but I wanted to put in my US$0.02 for UTF-8 instead of ISO-8859-1.

**Comment by srjfoo** [comment]
> ... UTF-8 is the default encoding for HTML5 which is certainly the future direction and has been around since 2014.

UTF-8 is also the preference for PG

**Comment by windymilla** [comment]
I agree with your comment, @cpeel, but there is a relevant Prefs settings explained below that I think changes the conclusion of your reasoning. I'm not sure PG's preference for utf-8 is directly related to the charset, @srjfoo, but more the encoding of the files - and of course for a file that only contains ascii characters, there is no difference between ascii/iso-8859-1/utf-8 encoding. Anyway, the argument below explains why I think the code logic is correct.

With or without my edit, Guiguts will mark the charset as utf-8 **by default** for ascii files (in fact for all HTML files). 
The only way to get iso-8859-1 as a charset is if the user explicitly disables the "Treat as utf-8" Prefs flag, which is enabled by default. In those circumstances, I don't think Guiguts should override the the user's choice. 

The only effect of my edit is that when the user has chosen not to treat the file as utf-8, instead of setting the charset to iso-8859-1 or ascii depending on file contents, it will always use iso-8859-1. 

Of course, even if the user has disabled "Always treat as utf-8", the charset will be set to utf-8 when the file contains curly quotes or other non-iso-8859-1 characters.

**Comment by cpeel** [comment]
Thanks for that additional detail, @windymilla!
