### ISSUE TITLE
The Surround Selection With will not take entries either from the Compose nor from the Commonly Used Characters Chart

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#759]
**Describe the solution you'd like**
I would like to be able to add “, left double quotation mark, as the left string and ”, right double quotation mark, as the right string in the Surround Selection With.

**Describe alternatives you've considered**

1. I tried the Tools=>Character Tools=>Compose Sequence but it adds the text to the document (a little upsetting since it replaces the text already selected to be surrounded).
2. Then I tried the Tools=>Character Tools=>Commonly Used Characters Chart. Oops, that had the same effect as alternative 1.
3. Finally, I used the Commonly Used Characters Chart to put the “” characters in the document then cut and pasted these into the Surround Selection With screen.

**Comment by windymilla** [comment]
Thanks for the report Rick. The only places you have ever been able to directly insert a character from the Commonly Used Characters dialog, or the Unicode Character Entry dialog, or the Unicode Blocks dialog, or the new Compose Sequence dialog, are the main text window, the search & replace box and the Greek dialog.

It is theoretically possible to make any of the text fields in any dialogs able to accept input from those special character generators, but each new place would have to be done individually, and for most it's obviously not really needed.  

You could shortcut your method a bit though - both the Common Characters chart and the Unicode block dialogs allow you to right-click a character to put it in the copy/paste buffer, which you could then paste directly into the Surround Selection With screen, instead of going via the main window.
1. Bring up Surround Selection With
2. Bring up Commonly Used Characters
3. **Right** click on left quotes
4. Paste into first field in Surround Selection
5. **Right** click on right quotes in Commonly Used Characters 
6. Paste into second field in Surround Selection

**Comment by okrick** [comment]
Thank you,  the right-click will be a time saver.
