### ISSUE TITLE
Small caps to All Caps appends replacement regex to existing text

### ISSUE THREAD

**Issue by maputan** [DistributedProofreaders/guiguts#763]
I've noticed a bug in 1.3.0, but I don't know if it's new in this version.

**Describe the bug**

When Txt>Small caps to All Caps is selected, the "replace" text is appended to anything in the "replace" box of the search and replace window, rather than replacing it.

**To Reproduce**

Start working on a text file.

Open the search and replace window.

Enter some text in the "replace" box.

Choose Txt>Small caps to All Caps.

 \U$1\E is appended to the entered text.

**Expected behavior**

\U$1\E replaces the entered text.

**Environment**
* Guiguts version: 1.3.0
* OS and version: archlinux
* Perl version: 1.3.0

**Comment by windymilla** [comment]
I've confirmed that behaviour - in fact it's just the first character in the replace field that is not cleared.
The bug was introduced in release 1.2 (#328 where fields were changed from Text to Entry type).

Notes for developer: There are a few places where it happens, in TextProcessingMenu.pm, all to do with case change:
`$::lglobal{replaceentry}->delete( '1.0', 'end' );`
should be something like
`$::lglobal{replaceentry}->delete( 0, 'end' );`
due to different method of indexing within Entry/Text fields.
