### ISSUE TITLE
Bookloupe error in "wrongspaced quotes" when a question mark is in the examined text

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#770]
This message appeared:

10:04:10: Guiguts 1.3.1: If you have any problems, please include any error messages that appear here with your bug report.
13:26:03: Tk::Error: bad text index "" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 Tk::__ANON__ at C:/Strawberry/perl/site/lib/Tk.pm line 251
 Guiguts::LineNumberText::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/LineNumberText.pm line 107
 Guiguts::ErrorCheck::errorcheckview at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/ErrorCheck.pm line 687
 Guiguts::ErrorCheck::__ANON__ at D:/Documents/DistrProof/PP/GG 1.3.1/lib/Guiguts/ErrorCheck.pm line 143
 <<remove>>
 (command bound to event)

when running Bookloupe's "Wrongspaced quotes" for the following text:

The following interesting letter is of uncertain
date:--

/#
/*
"<i>? 19th, ? 1881.</i>
"Down.
*/

"<sc>Dear Mr. Meldola</sc>,--When I read the F. M. [Fritz

(The closing #/ is later on.)  I think the error is caused by the presence of one or both of the question marks.  Entire file is available if needed. When question marks are replaced by x's, the line is not included in the possible errors list.

**Comment by windymilla** [comment]
Interesting one Charlie. The issue was that bookloupe outputs two identical errors for that file:
```
6:1 - Wrongspaced quotes?
6:1 - Wrongspaced quotes?
```
When you right click to delete the first, it removed all knowledge the system had of a "Wrongspaced quotes" error at 6:1, so then when it tried to show the second error, it failed to find the details it expected. Since I can't change bookloupe, and theoretically another tool could do a similar thing, I've made GG skip an error if it is identical and in the same location to one already stored. I can't see how it would be useful to the user to have the error message twice at the same location.

**Comment by charliehoward4dp** [comment]
Who woulda think of that? Impressive that you figured out what BL was doing, and found a solution, potentially useful elsewhere, for it.
