### ISSUE TITLE
Selecting text to the end of the line may fail to include the last character in the selection

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#805]
**Describe the bug**
I'm running split screen - that is, two application windows side by side - with the GG window to the right and an Irfanview window to the left. Thus the GG window is not full width. I have repeatedly encountered lines whose right most character just touches the right edge of the GG window and when I have wanted to select some text to the end of that line, the last character cannot be made part of the selection. In these cases there is no horizontal scroll bar present. I see this selection problem in 1.3.1 and 1.3.2. Have not managed to reproduce it in 1.3.0 or 1.0.25 but it may be there too.

**To Reproduce**
1. Open Guiguts 13.1. or 1.3.2.
2. Paste the line at 3 below into the window.
3. leeches in our rivers and in our seas, but<span class="pagenum" id="Page_124">[Pg 124]</span
4. Reduce width of GG window so that the rightmost character (">") just touches the right edge of the window AND the horizontal scrolling bar disappears. The position of the right-most character relative to the edge of the window is critical and may require very minor adjustment before the problem occurs - see comment under "expected behaviour".
5. Left click mid-way along the line and try to select the rest of the line to the scree edge. If the problem occurs the last character is not selected (i.e. highlighted in blue).

**Expected behavior**
I expect to be able to select all characters to the end of a line whether the horizontal scroll bar is present or not.

This is an "edge condition" in both software and physical terms! It only occurs when the last character of the line just touches the right edge of the GG window; the exact position is critical and you don't see the problem if the the window width is marginally adjusted. I believe I am only seeing this problem as I am running with a GG window that is narrower than normal so some of the text lines just happen to touch the right hand edge of the GG window _and_ the rest of the lines above and below that one in the GG window are all shorter. If any are wider the horizontal scroll bar is present and GG handles that situation gracefully.

**Environment**
* Guiguts version: 1.3.1, 1.3.2-pre1 (at least)
* OS and version:  Windows 10
* Perl version:  As required for GG 1.3.1+
* Perl distribution: 

**Screenshots**

**Additional context**
It is important to add that when this problem is occurring and you select PAST the last character of the line to include text on the next line, the selection process works as expected with the last character of the first line now being included in the selection.

**Comment by windymilla** [comment]
Hi - I can reproduce that successfully. However, the issue is caused by the way that screen x,y coordinates of the mouse are converted to character locations in the built-in Text widgets in Perl/Tk. You will have noticed that when you click to position the cursor, it often ends up one character to the left of where you expected it, at least compared to all other applications.  In other applications, if you click in the right half of a character, the cursor goes after it, and if in the left half, it goes before it. But in Text widgets, it goes before whichever character you click on, even if you're near the right hand edge of it.

Theoretically, it's possible to override any widget behaviour, but there are several places such as mouse clicking, dragging, etc., where the behaviour would have to be altered, and I don't think the risk and effort would be justified for the reward. The only workaround is to make your window slightly wider (or narrower) I'm afraid.

**Comment by srjfoo** [comment]
Does GG select a word on double-click?

I ask, because I thought I remembered that once upon a time, double-click meant select a word, triple-click meant select a line, and quadruple-click meant select a paragraph. I checked just now in Pages, BBEdit and LibreOffice, and apparently triple-click means select a paragraph for the first two, but for LO, it means "select a sentence". Does GG do anything like that?

Honestly, what I'm more inclined to do nowadays is to place the cursor at the beginning of a selction range, press the shift key, and use the arrow keys to get the selection range I want, but I can't check it out on GG right at this moment to see if that works. For instance, if I want the selection to go to the end of the line, I place the cursor, hold down shift-cmd (it's probably shift-ctrl on Windows) and press the right-arrow key.

**Comment by windymilla** [comment]
Double click does select word, and triple selects line, but that's it.

Yes, using Shift-End in Windows selects to end of line, including in the case described in the issue. If you have laptop/smaller keyboard, you may need to do something like Shift-Fn-F12 because there's no separate End key, but on a full size Windows keyboard, there is an End key which moves to end of line, so Shift-End selects to end of line.

The translation of mouse position to character location is a bit annoying in GG, and the issue is just a manifestation of that, but I think we'll have to live with it.

**Comment by windymilla** [comment]
Too built-in to the Tk widget's behavior to fix, unless it was causing serious problems for users.
