### ISSUE TITLE
"Scannos folder" filepath doesn't persist between guiguts sessions if set to path outside guiguts folder

### ISSUE THREAD

**Issue by susanskinner** [DistributedProofreaders/guiguts#815]
If I set a custom file path to my scannos folder that is outside the guiguts file structure, for example, E:\Users\susan\DP\scannos where E:\Users\susan\DP\guiguts is my guiguts install and close and re-open guiguts, the filepath been reset to "scannos". (The reset appears to happen when guiguts is next opened.) However, if I set it to another folder within the guiguts folder, say E:\Users\susan\DP\guiguts\wordlist then that persists between sessions.

The workaround is obviously to copy my custom scannos files into the guiguts folder but I like to keep them in a cloud-synced folder so that any updates are replicated across my devices, whereas I install guiguts in a non-cloud folder to avoid syncing conflicts from having it open on multiple devices.

i'm currently running 1.3.2 but the issue was there in at least 1.3.1 as well.

**Comment by windymilla** [comment]
Good news: the issue isn't quite as you've described, and it's easy for you to resolve. The trigger for the reset is not that your cloud-synced folder is outside the GG file structure; it's that your folder is called "scannos" (or more precisely, ends in "scannos" which is also the default name for the location under the GG structure). If you call your cloud-synced folder "scannoscloud", "scannos2", "scannoscustom", etc. (but not "myscannos") you can have it where you like and it won't be reset.

Bad news: I can't see a simple way to avoid this issue. The rationale behind GG's behaviour is that we were frequently getting "GG has stopped being able to run bookloupe/jeebies/scannos/etc" after people had updated their GG version. Older versions of GG stored the full path to the folder, e.g. "C:\DP\guiguts_1.1.1\scannos". They then installed 1.1.2, for example, and copied across settings from the old release to the new one, so it was still using the scannos folder from under the old release and they didn't notice. Some time later, they decided they didn't need 1.1.1 any more and deleted it, and their scannos folder was gone. 

So, to make it easier for newer or less technical users, when GG starts, it compares the tail of the path to the tool as stored in the settings file (e.g. C:\DP\guiguts_1.1.1\tools\bookloupe\bookloupe.exe") with the default location for the (new) release ("tools\bookloupe\bookloupe.exe") and if they are the same, it starts to use the new location, breaking the reliance on the old release. This works well for the tools since it's not likely the user has their own separate version that exactly matches tools\bookloupe\bookloupe.exe, but as you discovered, the default path to the scannos folder is just "scannos", which is more likely to be used as the name of a custom folder. 

If you are satisfied with that explanation and workaround (don't have your custom folder ending in the word "scannos"), I'd like you (or me) to close this issue, and I will ask Charlie to add a note in an appropriate place in the manual to document this slightly suprising behaviour.

**Comment by susanskinner** [comment]
Perfect - thanks! I've renamed my folder to scannos_custom and can confirm that that is now working as expected so I'm happy to close this.

**Comment by windymilla** [comment]
Thanks! I'll get onto Charlie about a note in the manual.
