### ISSUE TITLE
Bookloupe only ignores 3 of the 8 rewrap makers when checking for "Forward slash"

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#901]
**Describe the bug**
When Bookloupe looks for the "/" character in a file ["Forward slash" search enabled in options], it correctly ignores those characters when they are part of certain rewrap markers, namely /**/, /$$/ and /##/. In the case of the other five rewrap markers, however, the accompanying "/" characters are not ignored and thus queried by Bookloupe. This is inconsistent behaviour. 

**To Reproduce**
1. Open Guiguts with 
[rewrap-marker-test.txt](https://github.com/DistributedProofreaders/guiguts/files/8082647/rewrap-marker-test.txt)
2. Open the Tools>Bookloupe menu 
3. Enable "Forward slash" option in Options menu
4. Click "Run Checks" radio button
5. See which rewrap marker pairs the queried "/" characters are part of.

**Expected behavior**
I would expect the "/" character in any rewrap marker pair being ignored.

**Environment**
* Guiguts version: 1.4-test3
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**

**Comment by windymilla** [comment]
As you have described, this issue lies within bookloupe, because it is based on gutcheck, which pre-dates those "modern" rewrap markers. Since bookloupe is an external program to DP, its source code is not part of the Guiguts suite, so can't be altered within the current Guiguts development arrangements.
The longer term solution would be for someone to take on bookloupe development, but bearing in mind that it is used at PG, and it is therefore important that a new version of bookloupe does not miss errors that would subsequently be found by the WWers at PG. 
The short term solutions I've found so far have been hacking the way Guiguts processes the bookloupe output, e.g. to cope with its misspelling of "caret" and a capitalisation issue.
I think there may be a similar hack I could make to the input that Guiguts sends to bookloupe to address this problem. If it looks fairly safe, I'll try that.

By the way, for anyone keen to edit the bookloupe source, I think the edit that would be required is to add the "modern" rewrap markup to the array DPmarkup on line 109 of the file bookloupe.c
The array currently has `/*, /#, <tb>, etc,` but not the "modern" rewrap markup.
The code essentially strips those strings out of the lines it hands to the main bookloupe routine

**Comment by windymilla** [comment]
All rewrap markup will now be stripped before being sent to bookloupe under the following conditions:
1. It occurs at the beginning of the line
2. Nothing occurs after the markup on the line, except for optional margin settings in square brackets

This ensures that things like `/For some reason there's a slash here` or `/I used slash as markup for italic/` still get passed to bookloupe.

Note that running the test file through the new code results in a bookloupe error something like "This doesn't look like a text file", because essentially everything is stripped out from it. Adding some dummy text at the end stops the error occurring.
