### ISSUE TITLE
Add a block marker for right-justification

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#912]
Guiguts supports a centering tag, /f, although the manual's comment suggests its intended for Front Matter. Sometimes, it would be useful to have a right-alignment tag, e.g., /r. Like /f and /*, the text within it would be non-wrappable.

For Plain Text, the Rewrap Margins setting for "Block Max. Right Margin" could be used here as well, or a new option could be added for that.

For HTML, a new CSS class could be added to "Header.txt" and used in the generated code.

**Comment by windymilla** [comment]
I think this needs a bit more consideration to decide what is actually wanted, and how it fits in with what is already there. 

There is no markup that centers in the text version, and no markup that centers in the HTML version while preserving line breaks. There is a more [detailed description below](#details) of how things currently work to aid in decision making. 

There are two related existing options `Center Selection` and `Right-Align Selection` in the Txt menu. These appear to use Left Margin and Max Right Margin (not their Block equivalents) to determine positioning.

Specific questions are

1. Should line breaks be preserved in a new right-aligned and centered text block markup, i.e. don't rewrap? If so, what if the line is too long to fit in the space available - shouldn't happen of course :)
2. Should the margins used be the default left/right (not the block versions) to match the existing options in the Txt menu?
3. Do we need new entries in the Prefs->Rewrap Margins dialog rather than either of the above? This would mean the new feature wouldn't match the existing one.
4. Should any existing indentation prior to rewrapping be preserved / taken into account? It is not preserved by the existing Txt menu features. If it should be, how would that work?
5. It looks like `/$` is the closest to `Left-Align` markup that currently exists. Is it fit for purpose? Does its behavior shed light on how a new feature should work?
6. Should the new block markup (and potentially `/$`) also accept `[margins]` configuration, like block and index markup currently do, or is that overkill? Potentially, you could have `/$[10]` to specify a left margin of 10 (just like `/*`, except the default is zero, rather than the value in the Prefs->Rewrap Margins dialog). You could similarly specify a right margin for the new right-align feature (or perhaps an indent from the right, e.g. 4 spaces indent), and either a center column number or left & right margins for the centering feature. I don't think hanging indent would make sense for the new alignments. If those margins are necessary, then how should that translate to the HTML version? A margin-right could be used for the right-align case fairly easily, just like margin-left is used for the left-align. Perhaps centering not about the center is not worth the effort.

### <a name="details"></a>Details:
Some of the description of current behavior in the original issue is not accurate.
The `/f` tag doesn't do centering in the text version.
The `/f` tag does rewrap in the HTML version
For example
```
/f
line 1
  line 2
f/
```
Gives this in the text version:
```
/f
line 1
  line 2
f/
```
and this in the HTML version:
```
<p class="center">line 1
  line 2
</p>
```
which looks like this in a browser (centered)
```
                    line 1 line 2
```

Also to consider, the `/*` markup indents the block and preserves relative indentation, so
```
/*
line 1
  line 2
*/
```
gives this in the text version (if your default indent for /* blocks is 2). This can be overridden for a specific block with `/*[0]` to specify a zero indent (equivalent to `/$` below?)
```
/*
  line 1
    line 2
*/
```
and this in the HTML version:
```
<p>
line 1<br />
<span style="margin-left: 1em;">line 2</span><br />
</p>
```
which looks like this in a browser
```
line 1
  line 2
```

The `/$` markup is identical to `/*` in the HTML version. In the text version, it does not indent the whole block by 2 spaces, giving this:
```
/$
line 1
  line 2
$/
```

**Comment by rtonsing** [comment]
>     1. Should line breaks be preserved in a new right-aligned and centered text block markup, i.e. don't rewrap? If so, what if the line is too long to fit in the space available - shouldn't happen of course :)
yes, unless too long
> 
>     2. Should the margins used be the default left/right (not the block versions) to match the existing options in the Txt menu?
yes
> 
>     3. Do we need new entries in the Prefs->Rewrap Margins dialog rather than either of the above? This would mean the new feature wouldn't match the existing one.
no
> 
>     4. Should any existing indentation prior to rewrapping be preserved / taken into account? It is not preserved by the existing Txt menu features. If it should be, how would that work?
no
> 
>     5. It looks like `/$` is the closest to `Left-Align` markup that currently exists. Is it fit for purpose? 
yes
> 
>     6. Should the new block markup (and potentially `/$`) also accept `[margins]` configuration, like block and index markup currently do, or is that overkill? 
Would be nice for right, I usually right-indent a couple of spaces
> 
> 
> Some of the description of current behavior in the original issue is not accurate. The `/f` tag doesn't do centering in the text version. The `/f` tag does rewrap in the HTML version.
>
I would prefer no rewrap in HTML.

**Comment by charliehoward4dp** [comment]
There are two specific situations that prompted my request for a right-justification tag, both of which normally occur in letters & correspondence: 1) the block containing "From-location" and date at the top of a letter, and 2) the signature block at the bottom of a letter.

-  Neither should wrap
-  Ideally, leading spaces would be preserved, such that the right-most character in the block determines right-justification
-  If a line is too long to fit in Plain Text (which IMO is a PP's oversight), it should be indented by one character in Plain Text to prevent subsequent rewrapping by PG, and extend past the right margin
-  Using the existing PREFERENCES to derive Block Quote right-margin indentation is preferred, but going out to 72, as is done for "Right-justify numbers in selection" on the TXT menu, is fine
-  One-off overrides using /r\[n\] to indicate the RIGHT margin indent would be nice but not necessary, and could be confusing.

Regarding /f, I haven't tested it (was/am planning to do so today), assumed it worked for Plain Text as documented (I copied that from the old GG documentation), and believe it should be implemented if it doesn't work.  The lines within the /f block should not be rewrapped.  The use of this tag, beyond surrounding Front Matter, is for in-body lines that should be centered even though they are not Section headings.

For the most part, my replies below are the same as Robert's:

> I think this needs a bit more consideration to decide what is actually wanted, and how it fits in with what is already there.
> 
> There is no markup that centers in the text version, and no markup that centers in the HTML version while preserving line breaks. There is a more [detailed description below](#details) of how things currently work to aid in decision making.
> 
> There are two related existing options `Center Selection` and `Right-Align Selection` in the Txt menu. These appear to use Left Margin and Max Right Margin (not their Block equivalents) to determine positioning.
> 
> Specific questions are
> 
> 1. Should line breaks be preserved in a new right-aligned and centered text block markup, i.e. don't rewrap? If so, what if the line is too long to fit in the space available - shouldn't happen of course :)

Preserved: yes; too long: indent by 1 and let the rest extend past the right margin

> 2. Should the margins used be the default left/right (not the block versions) to match the existing options in the Txt menu?

The Prefs->Rewrap Margins' Block Quote right-margin could/should be used by default. Would always be used unless \[n\] is also implemented for /r.

> 3. Do we need new entries in the Prefs->Rewrap Margins dialog rather than either of the above? This would mean the new feature wouldn't match the existing one.

No

> 4. Should any existing indentation prior to rewrapping be preserved / taken into account? It is not preserved by the existing Txt menu features. If it should be, how would that work?

Yes. The line(s) within the tags comprise a Block. The Block should be shifted to the right until the rightmost nonblank character within the Block reaches the right margin.

> 5. It looks like `/$` is the closest to `Left-Align` markup that currently exists. Is it fit for purpose? Does its behavior shed light on how a new feature should work?

Provisionally, yes. I need to test it to be sure, as I only used it once, long ago.

> 6. Should the new block markup (and potentially `/$`) also accept `[margins]` configuration, like block and index markup currently do, or is that overkill? Potentially, you could have `/$[10]` to specify a left margin of 10 (just like `/*`, except the default is zero, rather than the value in the Prefs->Rewrap Margins dialog). You could similarly specify a right margin for the new right-align feature (or perhaps an indent from the right, e.g. 4 spaces indent), and either a center column number or left & right margins for the centering feature. I don't think hanging indent would make sense for the new alignments. If those margins are necessary, then how should that translate to the HTML version? A margin-right could be used for the right-align case fairly easily, just like margin-left is used for the left-align. Perhaps centering not about the center is not worth the effort.

This would be nice, but not necessary. For HTML, a new class will be needed in header.txt and used in the generated HTML body. That class should not be "right", which already is in use. To maintain ragged-right alignment will require additional work (which I hadn't thought about when making the original request; I have some CSS classes defined for use in spans to handle this, and &lt;br /&gt; at the end of each line in the right-justified block to prevent rewrap. If you decide to implement /r, we can go into more detail on this. One possibility is to generate css classes for right-padding the way GG generates text-indents for poetry indents.
> 
> ### Details:
> Some of the description of current behavior in the original issue is not accurate. The `/f` tag doesn't do centering in the text version. The `/f` tag does rewrap in the HTML version For example

(deleted the examples)

I didn't know any of that, and should have tested it before making the request, but it was late and the project I'm pp'ing has HUNDREDS of letters crying out for /r, and probably hundreds of lines that should remain centered in it.  It will make a dandy test case for an enhanced version of GG. ;-)

IMO, /f and /r should not rewrap in TEXT or HTML (for HTML, add &lt;br /&gt; to each line if not already present), the centerline for /f should be based on the parent block's margins (or the document's if there is no parent block), and the right margin for /r should be based on the parent block's right-margin (or the document's if there is no parent block).

This reply undoubtedly will be edited after further reflection.

**Comment by charliehoward4dp** [comment]
If /f is revamped so that it works, perhaps the tag's mnemonic should be /c instead of /f.

**Comment by windymilla** [comment]
I can't think of a practical way to treat the right aligned lines as a block in HTML, apart from something like an inline-block which I definitely don't want to get into. To be clear, I think what you are talking about is replicating something like:
```
                                                      146 Winterton Road
                                                      Leicester
                                                      UK
``` 
and ***not***
```
                                                      146 Winterton Road
                                                               Leicester
                                                                      UK
``` 
You want the address block right-aligned, but the lines within the block left-aligned, and ***not*** all the lines right-aligned individually.
Without using inline-block, the only other idea I can come up with is using padding-right. However, that wouldn't give accurate left-alignment, due to proportional font letter widths.
Any ideas?

**Comment by windymilla** [comment]
> If /f is revamped so that it works, perhaps the tag's mnemonic should be /c instead of /f.
Definitely. If we're changing both the text and HTML results, what we're actually producing is a new tag. No doubt someone loves `/f` exactly as it is.

**Comment by charliehoward4dp** [comment]
_Both_ sides of lines within an /R block likely are ragged. [HERE](https://archive.org/details/memoriesbyadmira00fishuoft/page/13/mode/1up) is the original image at TIA, and below is how the foofers and/or I aligned and marked it up in Plain Text (with most of the text of the letter omitted):

```
/#
/R
<sc>Roman Camp</sc>,
    <sc>Callander, N.B.</sc>
          <i>July 30, 1918.</i>
R/

/$
<sc>My dear Admiral</sc>,
$/

The pages are wonderful, because they are <i>you</i>.

Not a square inch of pose about them.
...
...
...

/R
Ever yours,
    My beloved Admiral,
                    <sc>Esher</sc>.
R/
#/
```

The rightmost character within each /R block should be at the right margin of the block's parent (perhaps also honoring `Preferences->Block right margin`), and right-padded whitespace should be replicated by using spans, as discussed in the next paragraph. (Some may prefer that the left-padded whitespace be replicated, as GG does with poetry. I don't have a strong preference.)  In the "From" block of this example, the date line is rightmost; in the "Signature" block, the sender's name is rightmost.  In other situations, other lines may be rightmost; I'm just trying to replicate what was printed.

In Plain Text, lines within an /R block need to be left-padded and not wrapped to achieve this.  In HTML generation, the block can open with `<p class="right">`; each line within it requiring some left-padding should be enclosed in a span such as `<span class="pr2">` (where the "pr2" class is defined as: `.pr2 class="padding-right: 2em;"`); and each line must end with a `<br />`. There should not be any `<span style="padding-left: 4em;">` as HTML Generation normally does when it sees leading whitespace.
