### ISSUE TITLE
F2 and F1 not working with Column Cut/Copy

### ISSUE THREAD

**Issue by jandac-2020** [DistributedProofreaders/guiguts#929]
When using GG to turn a one-column list into two columns via the Edit menu, the F2 and F1 buttons do not work as expected and do not cut/copy the selected list items to the clipboard. Similar malfunction if you click on the menu lines 'Column Cut' and 'Column Copy'.

But using Cntl X and Cntl C do of course cut and copy to clipboard as expected. And then F3 or 'Column Paste' work as expected and correctly give the two column result.

**To reproduce**
Open the attached file 'one-column list.txt' in GG
Select the last four lines of the list (item6 - item9)
Cut the selected lines with F2 or 'Column Cut'
Move cursor to column 30 (or thereabouts) of the top line of the list (item1)
Click F3.

**Expected behavior**
We should get the following result
(and do get it using Cntl X then F3)
```
aaaa item1                    fffffff item6    
bb item2                      ggggg item7
cccccc item3                  hhhhhhhhhh item8
dddd item4                    iii item9
eeeeeeeeeeeeeee item5
```

**Environment**
* Guiguts version:  1.3.3
* OS and version:  Windows 10
* Perl version: 
* Perl distribution:  Strawberry
* 

[one-column list.txt](https://github.com/DistributedProofreaders/guiguts/files/8639915/one-column.list.txt)

**Comment by windymilla** [comment]
Thanks for reporting this. I think it might be due to a misunderstanding of what column cut/copy does. The behaviour described is identical in all releases I can check, back to 1.0.25, and matches what I think it is intended to do.

Column cut/copy takes the start point of the selection, in this case Line 10: Col 0, and the end point, which I suspect you have as Line 14: Col 0 in order to select all of the last four lines. It then cuts/copies the rectangle of text from the start point to the end point. In your case, since the start and end are both at Col 0, this is zero width, so nothing is cut/copied.

If instead, you had selected the last 4 lines from L10:C0 to L13:C9, you will get something more like you were expecting, but not what you want. However, it illustrates what column cut/copy does.

To get what you want using column cut/paste, you need to add spaces onto the end of L13, so you can select from L10:C0 to L13:C16, then column cut. Then add spaces to the end of L5, so the cursor is positioned where you want the second column of your list to begin, then use column paste.

Alternatively, just cut the text using normal cut (Ctrl-X) as you describe, then column paste it onto the end of an extended line 5.

If that explanation is OK, you or I can close this issue.

**Comment by jandac-2020** [comment]
Always something new to learn about GG even after 5+ years.I was not doing a *columnar* selection, hence F2 and F1 did not work as I expected, and cntl-x of course did.
I did scan the manual before I raised the github issue, but I guess I only saw what I wanted to see, and missed the definition of 'columnar'.
Having played around with this new bauble, I understand what you were saying, and can get F2 and F1 to do my bidding. I find that I don't have to add padding spaces to line 13, just doing the shift-selection and ending on line 13 col 9 does the job.
I also hit the occasional anomaly, and needed to repeat a command or do a double undo -- but the manual gives fair warning of this too -- "Columnar selections are not consistently integrated with the rest of the editing facilities and you can get odd results when using them in ways not explicitly intended."
So please close the issue.And thank you for contributing to my continuing education.

    On Saturday, May 7, 2022, 07:09:52 AM EDT, Nigel ***@***.***> wrote:  
 
 


Thanks for reporting this. I think it might be due to a misunderstanding of what column cut/copy does. The behaviour described is identical in all releases I can check, back to 1.0.25, and matches what I think it is intended to do.

Column cut/copy takes the start point of the selection, in this case Line 10: Col 0, and the end point, which I suspect you have as Line 14: Col 0 in order to select all of the last four lines. It then cuts/copies the rectangle of text from the start point to the end point. In your case, since the start and end are both at Col 0, this is zero width, so nothing is cut/copied.

If instead, you had selected the last 4 lines from L10:C0 to L13:C9, you will get something more like you were expecting, but not what you want. However, it illustrates what column cut/copy does.

To get what you want using column cut/paste, you need to add spaces onto the end of L13, so you can select from L10:C0 to L13:C16, then column cut. Then add spaces to the end of L5, so the cursor is positioned where you want the second column of your list to begin, then use column paste.

Alternatively, just cut the text using normal cut (Ctrl-X) as you describe, then column paste it onto the end of an extended line 5.

If that explanation is OK, you or I can close this issue.

**Comment by windymilla** [comment]
Yes. Always new things to learn for me too. Thanks
