### ISSUE TITLE
<ctrl>+<backspace> (delete word backwards) and  <ctrl>+<delete> (delete word forwards ) don't work as expected

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#932]
**Describe the bug**
When using the keyboard shortcuts
    ctrl+Backspace -- delete word backwards
    ctrl+Delete -- delete word forwards
each fails to work as I expect them to work.

If the word is enclosed in any type of 'bracket', each shortcut will delete the first one it encounters plus any letter characters but stop at the opening/closing 'bracket' it encounters.

In the case of a word containing an apostrophe each shortcut behaves differently and does not delete the whole word, including the apostrophe. I describe how to demonstrate this behaviour below.

**To Reproduce**
1. Open Guiguts with 
[grocers-apostrophe.txt](https://github.com/DistributedProofreaders/guiguts/files/8743606/grocers-apostrophe.txt)
2. Position cursor just before the word **grocers'** and do ctrl+Delete. It will delete all but the apostrophe.
3. Undo that edit and position the cursor just after the apostrophe. Then do ctrl+Backspace and it will delete the whole of the word **grocers'**, including the apostrophe. This is inconsistent with the action in (2).
4. Now position the cursor just before the word **banana's** and do ctrl+Delete. It will delete the word up to the apostrophe.
5. Undo that edit and position the word at the end of the word **banana's**. Then do ctrl+Backspace and it will delete the letter "s" then stop. It is at least consistent with the action in (4) but in both cases I would expect the whole word to be deleted, including the apostrophe.

**Expected behavior**
If a word contains an apostrophe then I expect both forward and backward deletes to delete the whole word, including the apostrophe.

Where a word is enclosed in brackets I would expect either no deletion at all or if deletion is done then both brackets are deleted with the word they enclose.
 
**Environment**
* Guiguts version:  1.4.0-test4
* OS and version:  Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
If the word to be deleted contains certain non-ASCII characters such as Greek letters then the whole word is deleted, However inclusion of other non-ASCII characters in a word, such as the 'dagger' symbol (&#8224;), causes the actions for an apostrophe described above.

**Comment by windymilla** [comment]
The code is unchanged for the last 10 years, and uses the following algorithm (brackets show delete backwards version):
From the current insert point plus (minus) one character, delete up to the next (previous) non-word character, i.e. a character that matches the regex `\W`

The non-word thing explains the behaviour around Greek, since Greek characters are word characters.

The algorithm could be changed if people don't like what it currently does - I don't know if others have strong opinions or if there is a "standard" way to delete a word, for example in MS Word, deleting backwards through a word enclosed in brackets deletes the close bracket, then another delete removes the word, then another deletes the open bracket - a comma is similarly treated as though it were a "word" and is deleted, requiring another delete to remove the word that precedes it.
Any chanage

**Comment by G4OEU** [comment]
You've cited the behaviour of MS Word and that would be a good model to use for a discussion if a consensus is needed. It behaves in a consistent and acceptable way for the cases that I raised in this issue.

So, for example, in the case of **grocer's** and **grocers'** it deletes the whole word, including the apostrophes, unlike the behaviour of GG. Where a word is within brackets, again the behaviour of MS Word is consistent and reasonable.

**Comment by windymilla** [comment]
The situation is even worse: Ctrl+Left/Right arrow moves a word back or forward, but forward tends to go further than backward if there are multiple spaces or punctuation. Also, Shift+Ctrl+Right (to extend selection a word forward) doesn't move the same distance as just Ctrl+Right.

For consistency, 
1. whether moving, selecting or deleting, going Left or Right should work as mirrors of one another
2. selecting using Shift should move the cursor to the same point it would have without Shift
3. deleting should delete from the current cursor position up to the point the cursor would move to with Ctrl+Left/Right

MS Word's algorithm is something like this:
1. A "word" is a string of letters/numbers/apostrophes with space or punctuation-type characters around it. Or it can be a string of non-letters/numbers with space or letters/numbers around it, e.g. `abc."` is two "words" `abc` and `."`
2. If at the end of a word, delete forward/back to the end of the next/previous word.
3. If at the beginning of a word, delete forward/back to the beginning of the next/previous word.
4. If mid-word, delete forward/back to the end/beginning of the current word.
5. If there are multiple spaces between two words and the cursor is in the middle of that run of spaces, it is less consistent:
    a. Delete word backward deletes spaces backward and the previous word and space back to the end of the word before that.
    b. Delete word forward just deletes spaces up to the start of the next word, but doesn't delete that word.
6. There's another inconsistency with apostrophes, since they may actually be single quotes. For example, an apostrophe at the end or in the middle of a word is treated like a letter/number, but an apostrophe at the beginning is not. Also, a word enclosed in single quotes is deleted differently to one enclosed in double quotes. Note that hyphens are treated like punctuation.

I suggest we attempt to mimic the above, except for 5a, which should behave like 5b, since it's better to delete too little and have to hit Delete again, rather than switch to Undoing because it deleted too much.
To be considered, should apostrophe/single quote be treated as a letter/number, or as punctuation. I slightly favour punctuation for the same reason (better to delete too little), and it would be simpler, and it would remove the inconsistency with treatment of single quotes.
