### ISSUE TITLE
Enhancement - multi-select for actions on configure page labels

### ISSUE THREAD

**Issue by netsirk021** [DistributedProofreaders/guiguts#953]
Often when PPing, we have to mark many pages as no-count, because there are lots of illustrations, or PMs have split certain pages with multiple columns (especially the index). With long chunks of pages, it's a bit of a pain to click each one individually and change it to no count. It would be nice to be able to select many at once and change them all.

**Comment by netsirk021** [comment]
The commands are a bit different on Mac, but it seems like it still
requires you to go through each one one by one. Is there a way to do it all
at once for multiple pages?

**Comment by windymilla** [comment]
You do need to Ctrl+click once on each page in the list that you want to change. Unless I've misunderstood, the only advantage of a multi-select list would be where there are a lot of contiguous pages that you want to change. The most common cases I have seen are single illo (sometimes with a blank reverse, so 2 pages to "no count") and columns in the index as you mention. I don't think multi-select would help those situation, since for columns, you typically have to "no count" alternate scanned pages. 
In a typical multi-select list, the user clicks on the first entry to select, then uses something like Shift-click on the last entry in the range, then you would have to click the change you want to make. So multi-select would only save clicks where there are  4 or more "no counts" in a row.
It would be quite a bit of work, and involve changing the existing key combinations to change that list to a multi-select, but I would give it a try if people were happy with the changes and it would be used often enough to justify it.
If I've misunderstood, can you point me to an example please.

**Comment by srjfoo** [comment]
I'm not entirely sure what @netsirk021 is requesting, but I though I'd give an example of the different kinds of multi-select I typically use.

Take the DP project search as an example. If I want to select multiple languages, I can do one of two things -- if it's in a contiguous range, I click on the first one, scroll to the last one, and shift-click to select the whole range. If the languages I want are not contiguous, I can still select multiple languages, but I have to do a command-click on each language I want to add.

So, if they're contiguous, I just have to click on the first and last of the range, but you're right, if they're not contiguous, I have to click on each one that I want to add to the selections.

**Comment by windymilla** [comment]
I think that's correct, so you need 3 clicks to do anything. Start, end and action. Since you can click to act on one page, multi select only saves clicks if there are 4 or more contiguous pages that need changing

**Comment by windymilla** [comment]
Seems like this wouldn't justify the work and changes necessary, given the tools that already exist. Can always be reopened or a fresh issue raised if necessary.

**Comment by netsirk021** [comment]
I regularly set up No Count for multiple pages in a row in the front
matter, in sections with multiple pages of illustrations in a row, and also
in indices (and the occasional appendix), because I find that having page
numbers there isn't really very useful and it tends to get caught up in the
regex for linking page numbers. Maybe worth a query on the PP forums to see
how often other people are doing this, but if I'm the only one who would
find it useful and it's a lot of work to code, don't worry about it. It's
not like it's the only place where I do a lot of repetitive clicking in my
life :D My fingers can take it.

**Comment by windymilla** [comment]
Could you send me a typical file (plus the .bin file of course) with the page labels set as you want them please so I can have a concrete example. From the books I PPV, I think people generally retain page numbers everywhere the book has them, such as indices/appendices - I see that you would be likely to have several pages in a row that need No Counting if you decide to remove the page numbers for those.
The main causes for hesitation are as follows: old versions of GG had a different method of setting page numbers (where you selected pages and then applied the action to them) and there was a very positive reaction when I changed to the current method. Also, switching to a multi-select would definitely mean a change to the current mouse/keystrokes, which some people would not like. There would be a significant amount of coding, testing & documentation to be redone too.
Never say never, but I'm not convinced yet :)

**Comment by netsirk021** [comment]
I am not ignoring you, I promise. I just don't really keep all my old PP
files hanging around and I haven't been doing as much PP lately, so I
didn't have a great example handy. But I am picking back up my pile of PP
now and hopefully can share a good example with you soon.

**Comment by windymilla** [comment]
Agreed that existing feature, including Ctrl/Shift shortcuts is satisfactory, if not ideal.
