### ISSUE TITLE
Malformed footnote anchors in auto generate

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#962]
The attached files (pregen and postgen) use a non-standard numbering system for footnotes: `XXX-nn`, where `XXX` is the Chapter number (Roman numerals) and `nn` is the original footnote number in the book.  In the original book, the footnotes are endnotes at the end of the book. There were and still are many errors, omissions, and mismatches in the original book, so this is an attempt to match the ones that can be matched.

When Auto Generate runs, it [seems to] process the first 675 anchors correctly, but then scrambles occasional successive anchors and text.  This seems to happen when there are several anchors close to one another, perhaps separated by just one word.  Hard to explain but easy to see if you look at "h02-gen.html", which is what Auto Generate created from "h01-pregen.html".  "Tidy" flags many or all of them at once, while the Validators only flag the first one. Once the first one is corrected manually, the Validators flag the next one, etc.

These files also demonstrate a different, long-standing "auto generate" bug, where closing brackets are placed outside of closing `</p>'s` and `</div>'s`. I have a regex to find and fix those, so I haven't filed a bug report for it.

[footnote_generation_error.zip](https://github.com/DistributedProofreaders/guiguts/files/9176684/footnote_generation_error.zip)

**Comment by charliehoward4dp** [comment]
After reporting this issue, I tried several variations, but none of them made any difference.  Allowing Guiguts to renumber all the footnotes, without attempting to eliminate the "no anchor" and "out of sequence" errors, did allow Auto Generate to create valid syntax, but given the unresolvable errors in the original book, this generated result was not useful.

I did a successful workaround by creating the HTML anchors and footnotes with regexes instead of with Auto Generate, and realize this is an unusual, possibly unique situation. As such, trying to fix it may not be worthwhile.

The only change I hope to see for this in Guiguts is the generation of syntactically valid HTML, albeit with link errors.

**Comment by windymilla** [comment]
This may not be a complete explanation of all the issues, but I think it is the reason for the scrambled successive anchors, at least the first occurrence reported to me by the validator.
At line 17315 in h01-pregen.html, the footnote is numbered XXVI-16, when it should be XXVI-15. The issue is probably arising because it creates code for the anchor matching the first XXVI-16, then it tries to create code for the the anchor matching the second XXVI-16, so it ends up nesting one anchor inside the other. I hope that makes sense.
Certainly if you fix that issue, you get different results that look more correct in that area after autogen, and no validator error at line 14969 in the generated file.
Feel free to close this if you think that's a sufficient explanation - the footnotes and anchors must match up for autogen to work. However, if there are other issues relating to the footnotes in this file, I'm happy to look further.

**Comment by charliehoward4dp** [comment]
Since Auto Generate requires the footnotes and anchors to match, and that won't work with this pretty-much unique file, I'll just close the issue. Thank you for looking at it.
